insert into {destschemaname}.IHS4 
  SELECT YR, MON, QTR, RPT_CTY, CAST(HTS As VARCHAR(12)) As COMMODITY, 
  CAST(SUBSTRING(HTS,1,2) As VARCHAR(6)) As HTS, UNIT, PTN_CTY, 
  SUM(QUANTITY_) As QUANTITY_, SUM(VALUE_US) AS VALUE_US, SUM(QTY2) AS QTY2, UNIT2,
  RIGHT('0000' + CAST(YR AS NVARCHAR), 4)+RIGHT('0000' + CAST(mon AS NVARCHAR), 2)+[COMMODITY] as yrmoncomm 
  FROM 
  (
    SELECT YR, MON, QTR, RPT_CTY, CAST(HTS As VARCHAR(12)) AS COMMODITY, CAST(SUBSTRING(HTS,1,4) As VARCHAR(6)) As HTS, UNIT, PTN_CTY, 
    SUM(QUANTITY_) As QUANTITY_, SUM(VALUE_US) AS VALUE_US, SUM(QTY2) AS QTY2, UNIT2 
    FROM {destschemaname}.IHSA 
    GROUP BY HTS, SUBSTRING(hts,1,4), PTN_CTY, RPT_CTY,  YR, MON, QTR, UNIT, UNIT2
  )
  GROUP BY HTS, SUBSTRING(hts,1,2), PTN_CTY, RPT_CTY,  YR, MON, QTR, UNIT, UNIT2, COMMODITY;
