-- Script to create the Form-923 tables
DROP TABLE IF EXISTS {schemaName}.{tableName}P1GenFuel;
CREATE TABLE {schemaName}.{tableName}P1GenFuel
(
PlantId	integer,
CombinedHeatAndPowerPlant	varchar (10) ENCODE LZO,
NuclearUnitId	integer,
PlantName	varchar (100) ENCODE LZO,
OperatorName	varchar (100) ENCODE LZO,
OperatorId	integer,
PlantState	varchar (100) ENCODE LZO,
CensusRegion	varchar (10) ENCODE LZO,
NERCRegion	varchar (10) ENCODE LZO,
Reserved1	varchar (10) ENCODE LZO,
NAICSCode	integer,
EIASectorNumber	integer,
SectorName	varchar (100) ENCODE LZO,
ReportedPrimeMover	varchar (10) ENCODE LZO,
ReportedFuelTypeCode	varchar (10) ENCODE LZO,
AERFuelTypeCode	varchar (10) ENCODE LZO,
Reserved2	varchar (10) ENCODE LZO,
Reserved3	varchar (10) ENCODE LZO,
PhysicalUnitLabel	varchar (100) ENCODE LZO,
QuantityJanuary	varchar(10) ENCODE LZO,
QuantityFebruary	varchar(10) ENCODE LZO,
QuantityMarch	varchar(10) ENCODE LZO,
QuantityApril	varchar(10) ENCODE LZO,
QuantityMay	varchar(10) ENCODE LZO,
QuantityJune	varchar(10) ENCODE LZO,
QuantityJuly	varchar(10) ENCODE LZO,
QuantityAugust	varchar(10) ENCODE LZO,
QuantitySeptember	varchar(10) ENCODE LZO,
QuantityOctober	varchar(10) ENCODE LZO,
QuantityNovember	varchar(10) ENCODE LZO,
QuantityDecember	varchar(10) ENCODE LZO,
Elec_QuantityJanuary	varchar(10) ENCODE LZO,
Elec_QuantityFebruary	varchar(10) ENCODE LZO,
Elec_QuantityMarch	varchar(10) ENCODE LZO,
Elec_QuantityApril	varchar(10) ENCODE LZO,
Elec_QuantityMay	varchar(10) ENCODE LZO,
Elec_QuantityJune	varchar(10) ENCODE LZO,
Elec_QuantityJuly	varchar(10) ENCODE LZO,
Elec_QuantityAugust	varchar(10) ENCODE LZO,
Elec_QuantitySeptember	varchar(10) ENCODE LZO,
Elec_QuantityOctober	varchar(10) ENCODE LZO,
Elec_QuantityNovember	varchar(10) ENCODE LZO,
Elec_QuantityDecember	varchar(10) ENCODE LZO,
MMBtuPer_UnitJanuary	varchar(10) ENCODE LZO,
MMBtuPer_UnitFebruary	varchar(10) ENCODE LZO,
MMBtuPer_UnitMarch	varchar(10) ENCODE LZO,
MMBtuPer_UnitApril	varchar(10) ENCODE LZO,
MMBtuPer_UnitMay	varchar(10) ENCODE LZO,
MMBtuPer_UnitJune	varchar(10) ENCODE LZO,
MMBtuPer_UnitJuly	varchar(10) ENCODE LZO,
MMBtuPer_UnitAugust	varchar(10) ENCODE LZO,
MMBtuPer_UnitSeptember	varchar(10) ENCODE LZO,
MMBtuPer_UnitOctober	varchar(10) ENCODE LZO,
MMBtuPer_UnitNovember	varchar(10) ENCODE LZO,
MMBtuPer_UnitDecember	varchar(10) ENCODE LZO,
Tot_MMBtuJanuary	varchar(10) ENCODE LZO,
Tot_MMBtuFebruary	varchar(10) ENCODE LZO,
Tot_MMBtuMarch	varchar(10) ENCODE LZO,
Tot_MMBtuApril	varchar(10) ENCODE LZO,
Tot_MMBtuMay	varchar(10) ENCODE LZO,
Tot_MMBtuJune	varchar(10) ENCODE LZO,
Tot_MMBtuJuly	varchar(10) ENCODE LZO,
Tot_MMBtuAugust	varchar(10) ENCODE LZO,
Tot_MMBtuSeptember	varchar(10) ENCODE LZO,
Tot_MMBtuOctober	varchar(10) ENCODE LZO,
Tot_MMBtuNovember	varchar(10) ENCODE LZO,
Tot_MMBtuDecember	varchar(10) ENCODE LZO,
Elec_MMBtuJanuary	varchar(10) ENCODE LZO,
Elec_MMBtuFebruary	varchar(10) ENCODE LZO,
Elec_MMBtuMarch	varchar(10) ENCODE LZO,
Elec_MMBtuApril	varchar(10) ENCODE LZO,
Elec_MMBtuMay	varchar(10) ENCODE LZO,
Elec_MMBtuJune	varchar(10) ENCODE LZO,
Elec_MMBtuJuly	varchar(10) ENCODE LZO,
Elec_MMBtuAugust	varchar(10) ENCODE LZO,
Elec_MMBtuSeptember	varchar(10) ENCODE LZO,
Elec_MMBtuOctober	varchar(10) ENCODE LZO,
Elec_MMBtuNovember	varchar(10) ENCODE LZO,
Elec_MMBtuDecember	varchar(10) ENCODE LZO,
NetgenJanuary	varchar(10) ENCODE LZO,
NetgenFebruary	varchar(10) ENCODE LZO,
NetgenMarch	varchar(10) ENCODE LZO,
NetgenApril	varchar(10) ENCODE LZO,
NetgenMay	varchar(10) ENCODE LZO,
NetgenJune	varchar(10) ENCODE LZO,
NetgenJuly	varchar(10) ENCODE LZO,
NetgenAugust	varchar(10) ENCODE LZO,
NetgenSeptember	varchar(10) ENCODE LZO,
NetgenOctober	varchar(10) ENCODE LZO,
NetgenNovember	varchar(10) ENCODE LZO,
NetgenDecember	varchar(10) ENCODE LZO,
TotalFuelConsumptionQuantity	bigint,
ElectricFuelConsumptionQuantity	bigint,
TotalFuelConsumptionMMBtu	bigint,
ElecFuelConsumptionMMBtu	bigint,
NetGeneration_Megawatthours	float,
YEAR int
);

DROP TABLE IF EXISTS {schemaName}.{tableName}P2Stocks;
CREATE TABLE {schemaName}.{tableName}P2Stocks
(
Region_Name	varchar(100) ENCODE LZO,
Year		integer,
Coal_Jan	VARCHAR(10) ENCODE LZO,
Coal_Feb	VARCHAR(10) ENCODE LZO,
Coal_Mar	VARCHAR(10) ENCODE LZO,
Coal_Apr	VARCHAR(10) ENCODE LZO,
Coal_May	VARCHAR(10) ENCODE LZO,
Coal_Jun	VARCHAR(10) ENCODE LZO,
Coal_Jul	VARCHAR(10) ENCODE LZO,
Coal_Aug	VARCHAR(10) ENCODE LZO,
Coal_Sep	VARCHAR(10) ENCODE LZO,
Coal_Oct	VARCHAR(10) ENCODE LZO,
Coal_Nov	VARCHAR(10) ENCODE LZO,
Coal_Dec	VARCHAR(10) ENCODE LZO,
Oil_Jan		VARCHAR(10) ENCODE LZO,
Oil_Feb		VARCHAR(10) ENCODE LZO,
Oil_Mar		VARCHAR(10) ENCODE LZO,
Oil_Apr		VARCHAR(10) ENCODE LZO,
Oil_May		VARCHAR(10) ENCODE LZO,
Oil_Jun		VARCHAR(10) ENCODE LZO,
Oil_Jul		VARCHAR(10) ENCODE LZO,
Oil_Aug		VARCHAR(10) ENCODE LZO,
Oil_Sep		VARCHAR(10) ENCODE LZO,
Oil_Oct		VARCHAR(10) ENCODE LZO,
Oil_Nov		VARCHAR(10) ENCODE LZO,
Oil_Dec		VARCHAR(10) ENCODE LZO,
PetCoke_Jan	VARCHAR(10) ENCODE LZO,
PetCoke_Feb	VARCHAR(10) ENCODE LZO,
PetCoke_Mar	VARCHAR(10) ENCODE LZO,
PetCoke_Apr	VARCHAR(10) ENCODE LZO,
PetCoke_May	VARCHAR(10) ENCODE LZO,
PetCoke_Jun	VARCHAR(10) ENCODE LZO,
PetCoke_Jul	VARCHAR(10) ENCODE LZO,
PetCoke_Aug	VARCHAR(10) ENCODE LZO,
PetCoke_Sep	VARCHAR(10) ENCODE LZO,
PetCoke_Oct	VARCHAR(10) ENCODE LZO,
PetCoke_Nov	VARCHAR(10) ENCODE LZO,
PetCoke_Dec	VARCHAR(10) ENCODE LZO
);


DROP TABLE IF EXISTS {schemaName}.{tableName}P3BoilerFuel;
CREATE TABLE {schemaName}.{tableName}P3BoilerFuel
(
PlantId	bigint,
CombinedHeatAndPowerPlant	varchar (10) ENCODE LZO,
PlantName	varchar (100) ENCODE LZO,
OperatorName	varchar (100) ENCODE LZO,
OperatorId	float,
PlantState	varchar (10) ENCODE LZO,
CensusRegion	varchar (10) ENCODE LZO,
NERCRegion	varchar (10) ENCODE LZO,
NAICSCode	float,
SectorNumber	float,
SectorName	varchar (100) ENCODE LZO,
BoilerId	varchar (10) ENCODE LZO,
ReportedPrimeMover	varchar (10) ENCODE LZO,
ReportedFuelTypeCode	varchar (10) ENCODE LZO,
PhysicalUnitLabel	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedJanuary	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedFebruary	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedMarch	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedApril	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedMay	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedJune	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedJuly	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedAugust	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedSeptember	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedOctober	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedNovember	varchar (10) ENCODE LZO,
QuantityOfFuelConsumedDecember	varchar (10) ENCODE LZO,
MMbtuPerUnitJanuary	varchar (10) ENCODE LZO,
MMbtuPerUnitFebruary	varchar (10) ENCODE LZO,
MMbtuPerUnitMarch	varchar (10) ENCODE LZO,
MMbtuPerUnitApril	varchar (10) ENCODE LZO,
MMbtuPerUnitMay	varchar (10) ENCODE LZO,
MMbtuPerUnitJune	varchar (10) ENCODE LZO,
MMbtuPerUnitJuly	varchar (10) ENCODE LZO,
MMbtuPerUnitAugust	varchar (10) ENCODE LZO,
MMbtuPerUnitSeptember	varchar (10) ENCODE LZO,
MMbtuPerUnitOctober	varchar (10) ENCODE LZO,
MMbtuPerUnitNovember	varchar (10) ENCODE LZO,
MMbtuPerUnitDecember	varchar (10) ENCODE LZO,
SulfurContentJanuary	varchar (10) ENCODE LZO,
SulfurContentFebruary	varchar (10) ENCODE LZO,
SulfurContentMarch	varchar (10) ENCODE LZO,
SulfurContentApril	varchar (10) ENCODE LZO,
SulfurContentMay	varchar (10) ENCODE LZO,
SulfurContentJune	varchar (10) ENCODE LZO,
SulfurContentJuly	varchar (10) ENCODE LZO,
SulfurContentAugust	varchar (10) ENCODE LZO,
SulfurContentSeptember	varchar (10) ENCODE LZO,
SulfurContentOctober	varchar (10) ENCODE LZO,
SulfurContentNovember	varchar (10) ENCODE LZO,
SulfurContentDecember	varchar (10) ENCODE LZO,
AshContentJanuary	varchar (10) ENCODE LZO,
AshContentFebruary	varchar (10) ENCODE LZO,
AshContentMarch	varchar (10) ENCODE LZO,
AshContentApril	varchar (10) ENCODE LZO,
AshContentMay	varchar (10) ENCODE LZO,
AshContentJune	varchar (10) ENCODE LZO,
AshContentJuly	varchar (10) ENCODE LZO,
AshContentAugust	varchar (10) ENCODE LZO,
AshContentSeptember	varchar (10) ENCODE LZO,
AshContentOctober	varchar (10) ENCODE LZO,
AshContentNovember	varchar (10) ENCODE LZO,
AshContentDecember	varchar (10) ENCODE LZO,
TotalFuelConsumptionQuantity	float,
YEAR	float
);

DROP TABLE IF EXISTS {schemaName}.{tableName}P4Generator;
CREATE TABLE {schemaName}.{tableName}P4Generator
(
PlantId	integer,
CombinedHeatAndPowerPlant	varchar (10) ENCODE LZO,
PlantName	varchar (100) ENCODE LZO,
OperatorName	varchar (100) ENCODE LZO,
OperatorId	integer,
PlantState	varchar (10) ENCODE LZO,
CensusRegion	varchar (10) ENCODE LZO,
NERCRegion	varchar (10) ENCODE LZO,
NAICSCode	integer,
SectorNumber	integer,
SectorName	varchar (100) ENCODE LZO,
GeneratorId	varchar (10) ENCODE LZO,
ReportedPrimeMover	varchar (10) ENCODE LZO,
NetGenerationJanuary	varchar (10) ENCODE LZO,
NetGenerationFebruary	varchar (10) ENCODE LZO,
NetGenerationMarch	varchar (10) ENCODE LZO,
NetGenerationApril	varchar (10) ENCODE LZO,
NetGenerationMay	varchar (10) ENCODE LZO,
NetGenerationJune	varchar (10) ENCODE LZO,
NetGenerationJuly	varchar (10) ENCODE LZO,
NetGenerationAugust	varchar (10) ENCODE LZO,
NetGenerationSeptember	varchar (10) ENCODE LZO,
NetGenerationOctober	varchar (10) ENCODE LZO,
NetGenerationNovember	varchar (10) ENCODE LZO,
NetGenerationDecember	varchar (10) ENCODE LZO,
NetGenerationYearToDate	varchar (10) ENCODE LZO,
YEAR integer
);

DROP TABLE IF EXISTS {schemaName}.{tableName}P5FuelReceiptsAndCostsNoMercury;
CREATE TABLE {schemaName}.{tableName}P5FuelReceiptsAndCostsNoMercury
(
YEAR	integer,
MONTH	integer,
PlantId	integer,
PlantName	varchar (100) ENCODE LZO,
PlantState	varchar (10) ENCODE LZO,
PurchaseType	varchar (10) ENCODE LZO,
ContractExpirationDate	varchar(10) ENCODE LZO,
ENERGY_SOURCE	varchar (10) ENCODE LZO,
FUEL_GROUP	varchar (100) ENCODE LZO,
CoalmineType	varchar (10) ENCODE LZO,
CoalmineState	varchar (10) ENCODE LZO,
CoalmineCounty	varchar (10) ENCODE LZO,
CoalmineMshaId	varchar (10) ENCODE LZO,
CoalmineName	varchar (1000) ENCODE LZO,
SUPPLIER	varchar (1000) ENCODE LZO,
QUANTITY	float,
AverageHeatContent	float,
AverageSulfurContent	float,
AverageAshContent	float,
FUEL_COST	varchar (10) ENCODE LZO,
Regulated	varchar (100) ENCODE LZO,
OperatorName	varchar (100) ENCODE LZO,
OperatorId	varchar (100) ENCODE LZO,
ReportingFrequency	varchar (10) ENCODE LZO,
PrimaryTransportationMode	varchar (10) ENCODE LZO,
SecondaryTransportationMode	varchar (10) ENCODE LZO,
NaturalGasTransportationService	varchar (10) ENCODE LZO
);


DROP TABLE IF EXISTS {schemaName}.{tableName}P5FuelReceiptsAndCostsWithMercury;
CREATE TABLE {schemaName}.{tableName}P5FuelReceiptsAndCostsWithMercury
(
YEAR	integer,
MONTH	integer,
PlantId	integer,
PlantName	varchar (100) ENCODE LZO,
PlantState	varchar (10) ENCODE LZO,
PurchaseType	varchar (10) ENCODE LZO,
ContractExpirationDate	varchar(10) ENCODE LZO,
ENERGY_SOURCE	varchar (10) ENCODE LZO,
FUEL_GROUP	varchar (100) ENCODE LZO,
CoalmineType	varchar (10) ENCODE LZO,
CoalmineState	varchar (10) ENCODE LZO,
CoalmineCounty	varchar (10) ENCODE LZO,
CoalmineMshaId	varchar (10) ENCODE LZO,
CoalmineName	varchar (1000) ENCODE LZO,
SUPPLIER	varchar (1000) ENCODE LZO,
QUANTITY	float,
AverageHeatContent	float,
AverageSulfurContent	float,
AverageAshContent	float,
AverageMercuryContent	float,
FUEL_COST	varchar (10) ENCODE LZO,
Regulated	varchar (100) ENCODE LZO,
OperatorName	varchar (100) ENCODE LZO,
OperatorId	varchar (100) ENCODE LZO,
ReportingFrequency	varchar (10) ENCODE LZO,
PrimaryTransportationMode	varchar (10) ENCODE LZO,
SecondaryTransportationMode	varchar (10) ENCODE LZO,
NaturalGasTransportationService	varchar (10) ENCODE LZO
);

DROP TABLE IF EXISTS {schemaName}.{tableName}P6PlantFrame2011;
CREATE TABLE {schemaName}.{tableName}P6PlantFrame2011
(
YEAR	integer,
EIAPlantId	varchar(100) ENCODE LZO,
PlantName	varchar (100) ENCODE LZO,
PlantState	varchar (10) ENCODE LZO,
Sector	integer,
SectorName	varchar(100) ENCODE LZO,
NAICSCode	varchar(100) ENCODE LZO,
CombinedHeatAndPowerStatus	varchar (10) ENCODE LZO,
ReportingFrequency	varchar (10) ENCODE LZO,
NameplateCapacityMW varchar(10) ENCODE LZO
);

DROP TABLE IF EXISTS {schemaName}.{tableName}P6PlantFrame2012;
CREATE TABLE {schemaName}.{tableName}P6PlantFrame2012
(
YEAR	integer,
PlantId	varchar(100) ENCODE LZO,
PlantState	varchar (10) ENCODE LZO,
SectorNumber	integer,
NAICSCode	varchar(100) ENCODE LZO,
PlantName	varchar (100) ENCODE LZO,
CombinedHeatAndPowerStatus	varchar (10) ENCODE LZO,
ReportingFrequency	varchar (10) ENCODE LZO
);

DROP TABLE IF EXISTS {schemaName}.{tableName}P6PlantFrame2013;
CREATE TABLE {schemaName}.{tableName}P6PlantFrame2013
(
YEAR	integer,
EIAPlantId	varchar(100) ENCODE LZO,
PlantName	varchar (100) ENCODE LZO,
PlantState	varchar (10) ENCODE LZO,
Sector	integer,
SectorName	varchar(100) ENCODE LZO,
NAICSCode	varchar(100) ENCODE LZO,
CombinedHeatAndPowerStatus	varchar (10) ENCODE LZO,
ReportingFrequency	varchar (10) ENCODE LZO
);


DROP TABLE IF EXISTS {schemaName}.{tableName}P6PlantFrame2014to15;
CREATE TABLE {schemaName}.{tableName}P6PlantFrame2014to15
(
YEAR	integer,
PlantId	varchar(100) ENCODE LZO,
PlantState	varchar (10) ENCODE LZO,
SectorNumber	integer,
NAICSCode	varchar(100) ENCODE LZO,
PlantName	varchar (100) ENCODE LZO,
CombinedHeatAndPowerStatus	varchar (10) ENCODE LZO,
ReportingFrequency	varchar (10) ENCODE LZO
);

DROP TABLE IF EXISTS {schemaName}.{tableName}P6PlantFrame2016Onwards;
CREATE TABLE {schemaName}.{tableName}P6PlantFrame2016Onwards
(
YEAR	integer,
MONTH	integer,
PlantId	varchar(100) ENCODE LZO,
PlantState	varchar (10) ENCODE LZO,
SectorNumber	integer,
NAICSCode	varchar(100) ENCODE LZO,
PlantName	varchar (100) ENCODE LZO,
CombinedHeatAndPowerStatus	varchar (10) ENCODE LZO,
ReportingFrequency	varchar (10) ENCODE LZO
);

DROP TABLE IF EXISTS {schemaName}.{tableName}SourceDispositionTill2011;
CREATE TABLE {schemaName}.{tableName}SourceDispositionTill2011
(
Year	integer,
UtilityID	varchar(10) ENCODE LZO,
UtilityName	varchar(50) ENCODE LZO,
SectorCode	varchar(10) ENCODE LZO,
PlantCode	integer,
CHPPlant	varchar(1),
PlantName	varchar(50) ENCODE LZO,
PlantState	varchar(10) ENCODE LZO,
GrossGeneration	varchar(20) ENCODE LZO,
IncomingElectricity	varchar(20) ENCODE LZO,
TotalSource	varchar(20) ENCODE LZO,
StationUse	varchar(20) ENCODE LZO,
DirectUse	varchar(20) ENCODE LZO,
TotalFacilityUse	varchar(20) ENCODE LZO,
RetailSales	varchar(20) ENCODE LZO,
SalesforResale	varchar(20) ENCODE LZO,
OutgoingElectricity	varchar(20) ENCODE LZO,
Total_Disposition	varchar(20) ENCODE LZO,
RevenuefromResale	varchar(20) ENCODE LZO
);


DROP TABLE IF EXISTS {schemaName}.{tableName}SourceDisposition2012Onwards;
CREATE TABLE {schemaName}.{tableName}SourceDisposition2012Onwards
(
Year	integer,
UtilityID	varchar(10) ENCODE LZO,
UtilityName	varchar(50) ENCODE LZO,
SectorCode	varchar(10) ENCODE LZO,
PlantCode	integer,
CHPPlant	varchar(1),
PlantName	varchar(50) ENCODE LZO,
PlantState	varchar(10) ENCODE LZO,
GrossGeneration	varchar(20) ENCODE LZO,
IncomingElectricity	varchar(20) ENCODE LZO,
TotalSource	varchar(20) ENCODE LZO,
StationUse	varchar(20) ENCODE LZO,
DirectUse	varchar(20) ENCODE LZO,
TotalFacilityUse	varchar(20) ENCODE LZO,
RetailSales	varchar(20) ENCODE LZO,
SalesforResale	varchar(20) ENCODE LZO,
TollingAgreements	varchar(20) ENCODE LZO,
OutgoingElectricity	varchar(20) ENCODE LZO,
Total_Disposition	varchar(20) ENCODE LZO,
RevenuefromResale	varchar(20) ENCODE LZO,
TypesofIncomingElectricity	varchar(500) ENCODE LZO,
TypesofOutgoingElectricity	varchar(500) ENCODE LZO
);

--SELECT top 50 * FROM stl_load_errors order by starttime desc;