SELECT 
	series_id,
	series_key,
	mnemonic_source,
	mnemonic,
	Dri_mnemonic,
	Wefa_mnemonic,
	frequency,
	seriestype,
	startdate,
	enddate,
	REPLACE(shortlabel,'|',',') AS shortlabel,
	REPLACE(longlabel,'|',',') AS longlabel,
	conversion,
	distribution,
	decimals,
	status,
	concept,
	geo,
	unit,
	scale,
	industry,
	keyindicator,
	giirecommended,
	realnominal,
	seasonaladjustment,
	bank,
	source,
	timestamp,
	wefa_version 
FROM IDDS03.dbo.series_attr