DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_1_generatoroperable CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_1_generatoroperable
(
    UtilityID	                                                    INTEGER,
    UtilityName	                                                    VARCHAR(100) ENCODE LZO,
    PlantCode	                                                    INTEGER,
    PlantName	                                                    VARCHAR(100) ENCODE LZO,
    State		                                                    VARCHAR(100) ENCODE LZO,
    County		                                                    VARCHAR(100) ENCODE LZO,
    GeneratorID	                                                    VARCHAR(100) ENCODE LZO,
    Technology	                                                    VARCHAR(100) ENCODE LZO,
    PrimeMover	                                                    VARCHAR(100) ENCODE LZO,
    UnitCode	                                                    VARCHAR(100) ENCODE LZO,
    Ownership														VARCHAR(100) ENCODE LZO,
    DuctBurners														VARCHAR(100) ENCODE LZO,
    CanBypassHeatRecoverySteamGenerator								VARCHAR(100) ENCODE LZO,
    RTO_ISOLMPNodeDesignation										VARCHAR(100) ENCODE LZO,
    RTO_ISOLocationDesignationforReportingWholesaleSalesDatatoFERC	VARCHAR(100) ENCODE LZO,
    NameplateCapacity_MW	                                        FLOAT NULL,
    NameplatePowerFactor	                                        VARCHAR(100) ENCODE LZO,
    SummerCapacity_MW	                                            FLOAT NULL,
    WinterCapacity_MW	                                            FLOAT NULL,
    MinimumLoad_MW	                                                FLOAT NULL,
    UprateorDerateCompletedDuringYear	                            VARCHAR(100) ENCODE LZO,
    MonthUprateorDerateCompleted	                                VARCHAR(100) ENCODE LZO,
    YearUprateorDerateCompleted	                                    VARCHAR(100) ENCODE LZO,
    Status	                                                        VARCHAR(100) ENCODE LZO,
    SynchronizedtoTransmissionGrid	                                VARCHAR(100) ENCODE LZO,
    OperatingMonth	                                                VARCHAR(100) ENCODE LZO,
    OperatingYear	                                                VARCHAR(100) ENCODE LZO,
    PlannedRetirementMonth	                                        VARCHAR(100) ENCODE LZO,
    PlannedRetirementYear	                                        VARCHAR(100) ENCODE LZO,
    AssociatedwithCombinedHeatandPowerSystem	                    VARCHAR(100) ENCODE LZO,
    SectorName	                                                    VARCHAR(100) ENCODE LZO,
    Sector	                                                        VARCHAR(100) ENCODE LZO,
    ToppingorBottoming	                                            VARCHAR(100) ENCODE LZO,
    EnergySource1	                                                VARCHAR(100) ENCODE LZO,
    EnergySource2	                                                VARCHAR(100) ENCODE LZO,
    EnergySource3	                                                VARCHAR(100) ENCODE LZO,
    EnergySource4	                                                VARCHAR(100) ENCODE LZO,
    EnergySource5	                                                VARCHAR(100) ENCODE LZO,
    EnergySource6	                                                VARCHAR(100) ENCODE LZO,
    StartupSource1	                                                VARCHAR(100) ENCODE LZO,
    StartupSource2	                                                VARCHAR(100) ENCODE LZO,
    StartupSource3	                                                VARCHAR(100) ENCODE LZO,
    StartupSource4	                                                VARCHAR(100) ENCODE LZO,
    SolidFuelGasificationSystem	                                    VARCHAR(100) ENCODE LZO,
    CarbonCaptureTechnology	                                        VARCHAR(100) ENCODE LZO,
    Turbines_Inverters_orHydrokineticBuoys	                        VARCHAR(100) ENCODE LZO,
    TimefromColdShutdowntoFullLoad	                                VARCHAR(100) ENCODE LZO,
    FluidizedBedTechnology	                                        VARCHAR(100) ENCODE LZO,
    PulverizedCoalTechnology	                                    VARCHAR(100) ENCODE LZO,
    StokerTechnology	                                            VARCHAR(100) ENCODE LZO,
    OtherCombustionTechnology	                                    VARCHAR(100) ENCODE LZO,
    SubcriticalTechnology	                                        VARCHAR(100) ENCODE LZO,
    SupercriticalTechnology	                                        VARCHAR(100) ENCODE LZO,
    UltrasupercriticalTechnology	                                VARCHAR(100) ENCODE LZO,
    PlannedNetSummerCapacityUprate_MW	                            FLOAT NULL,
    PlannedNetWinterCapacityUprate_MW	                            FLOAT NULL,
    PlannedUprateMonth	                                            VARCHAR(100) ENCODE LZO,
    PlannedUprateYear	                                            VARCHAR(100) ENCODE LZO,
    PlannedNetSummerCapacityDerate_MW	                            FLOAT NULL,
    PlannedNetWinterCapacityDerate_MW	                            FLOAT NULL,
    PlannedDerateMonth	                                            VARCHAR(100) ENCODE LZO,
    PlannedDerateYear	                                            VARCHAR(100) ENCODE LZO,
    PlannedNewPrimeMover	                                        VARCHAR(100) ENCODE LZO,
    PlannedEnergySource1	                                        VARCHAR(100) ENCODE LZO,
    PlannedNewNameplateCapacity_MW	                                FLOAT,
    PlannedRepowerMonth	                                            VARCHAR(100) ENCODE LZO,
    PlannedRepowerYear	                                            VARCHAR(100) ENCODE LZO,
    OtherPlannedModifications	                                    VARCHAR(100) ENCODE LZO,
    OtherModificationsMonth	                                        VARCHAR(100) ENCODE LZO,
    OtherModificationsYear	                                        VARCHAR(100) ENCODE LZO,
    CofireFuels	                                                    VARCHAR(100) ENCODE LZO,
    SwitchBetweenOilandNaturalGas	                                VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_1_generatoroperable
(
    utilityid,
    utilityname,
    plantcode,
    plantname,
    state,
    county,
    generatorid,
    technology,
    primemover,
    unitcode,
    ownership,
    ductburners,
    canbypassheatrecoverysteamgenerator,
    rto_isolmpnodedesignation,
    rto_isolocationdesignationforreportingwholesalesalesdatatoferc,
    nameplatecapacity_mw,
    nameplatepowerfactor,
    summercapacity_mw,
    wintercapacity_mw,
    minimumload_mw,
    uprateorderatecompletedduringyear,
    monthuprateorderatecompleted,
    yearuprateorderatecompleted,
    status,
    synchronizedtotransmissiongrid,
    operatingmonth,
    operatingyear,
    plannedretirementmonth,
    plannedretirementyear,
    associatedwithcombinedheatandpowersystem,
    sectorname,
    sector,
    toppingorbottoming,
    energysource1,
    energysource2,
    energysource3,
    energysource4,
    energysource5,
    energysource6,
    startupsource1,
    startupsource2,
    startupsource3,
    startupsource4,
    solidfuelgasificationsystem,
    carboncapturetechnology,
    turbines_inverters_orhydrokineticbuoys,
    timefromcoldshutdowntofullload,
    fluidizedbedtechnology,
    pulverizedcoaltechnology,
    stokertechnology,
    othercombustiontechnology,
    subcriticaltechnology,
    supercriticaltechnology,
    ultrasupercriticaltechnology,
    plannednetsummercapacityuprate_mw,
    plannednetwintercapacityuprate_mw,
    plannedupratemonth,
    planneduprateyear,
    plannednetsummercapacityderate_mw,
    plannednetwintercapacityderate_mw,
    plannedderatemonth,
    plannedderateyear,
    plannednewprimemover,
    plannedenergysource1,
    plannednewnameplatecapacity_mw,
    plannedrepowermonth,
    plannedrepoweryear,
    otherplannedmodifications,
    othermodificationsmonth,
    othermodificationsyear,
    cofirefuels,
    switchbetweenoilandnaturalgas
)
SELECT
    utilityid,
    utilityname,
    plantcode,
    plantname,
    state,
    county,
    generatorid,
    technology,
    primemover,
    unitcode,
    ownership,
    ductburners,
    canbypassheatrecoverysteamgenerator,
    rto_isolmpnodedesignation,
    rto_isolocationdesignationforreportingwholesalesalesdatatoferc,
    CAST(CASE WHEN TRIM(nameplatecapacity_mw)='' THEN NULL ELSE nameplatecapacity_mw END AS FLOAT) AS nameplatecapacity_mw,
    nameplatepowerfactor,
    CAST(CASE WHEN TRIM(summercapacity_mw)='' THEN NULL ELSE summercapacity_mw END AS FLOAT) AS summercapacity_mw,
    CAST(CASE WHEN TRIM(wintercapacity_mw)='' THEN NULL ELSE wintercapacity_mw END AS FLOAT) AS wintercapacity_mw,
    CAST(CASE WHEN TRIM(minimumload_mw)='' THEN NULL ELSE minimumload_mw END AS FLOAT) AS minimumload_mw,
    uprateorderatecompletedduringyear,
    monthuprateorderatecompleted,
    yearuprateorderatecompleted,
    status,
    synchronizedtotransmissiongrid,
    operatingmonth,
    operatingyear,
    plannedretirementmonth,
    plannedretirementyear,
    associatedwithcombinedheatandpowersystem,
    sectorname,
    sector,
    toppingorbottoming,
    energysource1,
    energysource2,
    energysource3,
    energysource4,
    energysource5,
    energysource6,
    startupsource1,
    startupsource2,
    startupsource3,
    startupsource4,
    solidfuelgasificationsystem,
    carboncapturetechnology,
    turbines_inverters_orhydrokineticbuoys,
    timefromcoldshutdowntofullload,
    fluidizedbedtechnology,
    pulverizedcoaltechnology,
    stokertechnology,
    othercombustiontechnology,
    subcriticaltechnology,
    supercriticaltechnology,
    ultrasupercriticaltechnology,
    CAST(CASE WHEN TRIM(plannednetsummercapacityuprate_mw)='' THEN NULL ELSE plannednetsummercapacityuprate_mw END AS FLOAT) AS plannednetsummercapacityuprate_mw,
    CAST(CASE WHEN TRIM(plannednetwintercapacityuprate_mw)='' THEN NULL ELSE plannednetwintercapacityuprate_mw END AS FLOAT) AS plannednetwintercapacityuprate_mw,
    plannedupratemonth,
    planneduprateyear,
    CAST(CASE WHEN TRIM(plannednetsummercapacityderate_mw)='' THEN NULL ELSE plannednetsummercapacityderate_mw END AS FLOAT) AS plannednetsummercapacityderate_mw,
    CAST(CASE WHEN TRIM(plannednetwintercapacityderate_mw)='' THEN NULL ELSE plannednetwintercapacityderate_mw END AS FLOAT) AS plannednetwintercapacityderate_mw,
    plannedderatemonth,
    plannedderateyear,
    plannednewprimemover,
    plannedenergysource1,
    CAST(CASE WHEN TRIM(plannednewnameplatecapacity_mw)='' THEN NULL ELSE plannednewnameplatecapacity_mw END AS FLOAT) AS plannednewnameplatecapacity_mw,
    plannedrepowermonth,
    plannedrepoweryear,
    otherplannedmodifications,
    othermodificationsmonth,
    othermodificationsyear,
    cofirefuels,
    switchbetweenoilandnaturalgas
FROM {schemaName}.{tableName}3_1_generatoroperable;


DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_1_generatorproposed CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_1_generatorproposed
(
   utilityid                                 INTEGER,
   utilityname                               VARCHAR(100) ENCODE LZO,
   plantcode                                 VARCHAR(100) ENCODE LZO,
   plantname                                 VARCHAR(100) ENCODE LZO,
   state                                     VARCHAR(100) ENCODE LZO,
   county                                    VARCHAR(100) ENCODE LZO,
   generatorid                               VARCHAR(100) ENCODE LZO,
   technology                                VARCHAR(100) ENCODE LZO,
   primemover                                VARCHAR(100) ENCODE LZO,
   unitcode                                  VARCHAR(100) ENCODE LZO,
   ownership                                 VARCHAR(100) ENCODE LZO,
   ductburners                               VARCHAR(100) ENCODE LZO,
   canbypassheatrecoverysteamgenerator       VARCHAR(100) ENCODE LZO,
   rto_isolmpnodedesignation                 VARCHAR(100) ENCODE LZO,
   rto_isolocationdesignation                VARCHAR(100) ENCODE LZO,
   nameplatecapacity_mw                      FLOAT NULL,
   nameplatepowerfactor                      VARCHAR(100) ENCODE LZO,
   summercapacity_mw                         FLOAT NULL,
   wintercapacity_mw                         FLOAT NULL,
   status                                    VARCHAR(100) ENCODE LZO,
   effectivemonth                            VARCHAR(100) ENCODE LZO,
   effectiveyear                             VARCHAR(100) ENCODE LZO,
   currentmonth                              VARCHAR(100) ENCODE LZO,
   currentyear                               VARCHAR(100) ENCODE LZO,
   associatedwithcombinedheatandpowersystem  VARCHAR(100) ENCODE LZO,
   sectorname                                VARCHAR(100) ENCODE LZO,
   sector                                    VARCHAR(100) ENCODE LZO,
   previouslycanceled                        VARCHAR(100) ENCODE LZO,
   energysource1                             VARCHAR(100) ENCODE LZO,
   energysource2                             VARCHAR(100) ENCODE LZO,
   energysource3                             VARCHAR(100) ENCODE LZO,
   energysource4                             VARCHAR(100) ENCODE LZO,
   energysource5                             VARCHAR(100) ENCODE LZO,
   energysource6                             VARCHAR(100) ENCODE LZO,
   turbines_inverters_orhydrokineticbuoys    VARCHAR(100) ENCODE LZO,
   fluidizedbedtechnology                    VARCHAR(100) ENCODE LZO,
   pulverizedcoaltechnology                  VARCHAR(100) ENCODE LZO,
   stokertechnology                          VARCHAR(100) ENCODE LZO,
   othercombustiontechnology                 VARCHAR(100) ENCODE LZO,
   subcriticaltechnology                     VARCHAR(100) ENCODE LZO,
   supercriticaltechnology                   VARCHAR(100) ENCODE LZO,
   ultrasupercriticaltechnology              VARCHAR(100) ENCODE LZO,
   solidfuelgasificationsystem               VARCHAR(100) ENCODE LZO,
   carboncapturetechnology                   VARCHAR(100) ENCODE LZO,
   switchbetweenoilandnaturalgas             VARCHAR(100) ENCODE LZO,
   cofirefuels                               VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_1_generatorproposed
(
    utilityid,
    utilityname,
    plantcode,
    plantname,
    state,
    county,
    generatorid,
    technology,
    primemover,
    unitcode,
    ownership,
    ductburners,
    canbypassheatrecoverysteamgenerator,
    rto_isolmpnodedesignation,
    rto_isolocationdesignation,
    nameplatecapacity_mw,
    nameplatepowerfactor,
    summercapacity_mw,
    wintercapacity_mw,
    status,
    effectivemonth,
    effectiveyear,
    currentmonth,
    currentyear,
    associatedwithcombinedheatandpowersystem,
    sectorname,
    sector,
    previouslycanceled,
    energysource1,
    energysource2,
    energysource3,
    energysource4,
    energysource5,
    energysource6,
    turbines_inverters_orhydrokineticbuoys,
    fluidizedbedtechnology,
    pulverizedcoaltechnology,
    stokertechnology,
    othercombustiontechnology,
    subcriticaltechnology,
    supercriticaltechnology,
    ultrasupercriticaltechnology,
    solidfuelgasificationsystem,
    carboncapturetechnology,
    switchbetweenoilandnaturalgas,
    cofirefuels    
)
SELECT
    utilityid,
    utilityname,
    plantcode,
    plantname,
    state,
    county,
    generatorid,
    technology,
    primemover,
    unitcode,
    ownership,
    ductburners,
    canbypassheatrecoverysteamgenerator,
    rto_isolmpnodedesignation,
    rto_isolocationdesignation,
    CAST(CASE WHEN TRIM(nameplatecapacity_mw)='' THEN NULL ELSE nameplatecapacity_mw END AS FLOAT) AS nameplatecapacity_mw,
    nameplatepowerfactor,
    CAST(CASE WHEN TRIM(summercapacity_mw)='' THEN NULL ELSE summercapacity_mw END AS FLOAT) AS summercapacity_mw,
    CAST(CASE WHEN TRIM(wintercapacity_mw)='' THEN NULL ELSE wintercapacity_mw END AS FLOAT) AS wintercapacity_mw,
    status,
    effectivemonth,
    effectiveyear,
    currentmonth,
    currentyear,
    associatedwithcombinedheatandpowersystem,
    sectorname,
    sector,
    previouslycanceled,
    energysource1,
    energysource2,
    energysource3,
    energysource4,
    energysource5,
    energysource6,
    turbines_inverters_orhydrokineticbuoys,
    fluidizedbedtechnology,
    pulverizedcoaltechnology,
    stokertechnology,
    othercombustiontechnology,
    subcriticaltechnology,
    supercriticaltechnology,
    ultrasupercriticaltechnology,
    solidfuelgasificationsystem,
    carboncapturetechnology,
    switchbetweenoilandnaturalgas,
    cofirefuels
FROM {schemaName}.{tableName}3_1_generatorproposed;




DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_1_generatorretcancelled CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_1_generatorretcancelled
(
    UtilityID								    INTEGER,
	UtilityName								    VARCHAR(100) ENCODE LZO,
	PlantCode								    VARCHAR(100) ENCODE LZO,
	PlantName								    VARCHAR(100) ENCODE LZO,
	State									    VARCHAR(100) ENCODE LZO,
	County									    VARCHAR(100) ENCODE LZO,
	GeneratorID								    VARCHAR(100) ENCODE LZO,
	Technology								    VARCHAR(100) ENCODE LZO,
	PrimeMover								    VARCHAR(100) ENCODE LZO,
	UnitCode								    VARCHAR(100) ENCODE LZO,
	Ownership								    VARCHAR(100) ENCODE LZO,
	DuctBurners								    VARCHAR(100) ENCODE LZO,
	CanBypassHeatRecoverySteamGenerator		    VARCHAR(100) ENCODE LZO,
	RTO_ISOLMPNodeDesignation				    VARCHAR(100) ENCODE LZO,
	RTO_ISOLocationDesignation				    VARCHAR(100) ENCODE LZO,
	NameplateCapacity_MW					    FLOAT NULL,
	NameplatePowerFactor					    VARCHAR(100) ENCODE LZO,
	SummerCapacity_MW						    FLOAT NULL,
	WinterCapacity_MW						    FLOAT NULL,
	MinimumLoad_MW							    FLOAT NULL,
	UprateorDerateCompletedDuringYear		    VARCHAR(100) ENCODE LZO,
	MonthUprateorDerateCompleted			    VARCHAR(100) ENCODE LZO,
	YearUprateorDerateCompleted				    VARCHAR(100) ENCODE LZO,
	Status									    VARCHAR(100) ENCODE LZO,
	SynchronizedtoTransmissionGrid			    VARCHAR(100) ENCODE LZO,
	OperatingMonth							    VARCHAR(100) ENCODE LZO,
	OperatingYear							    VARCHAR(100) ENCODE LZO,
	RetirementMonth							    VARCHAR(100) ENCODE LZO,
	RetirementYear							    VARCHAR(100) ENCODE LZO,
	AssociatedwithCombinedHeatandPowerSystem    VARCHAR(100) ENCODE LZO,
	SectorName								    VARCHAR(100) ENCODE LZO,
	Sector									    VARCHAR(100) ENCODE LZO,
	ToppingorBottoming						    VARCHAR(100) ENCODE LZO,
	EnergySource1							    VARCHAR(100) ENCODE LZO,
	EnergySource2							    VARCHAR(100) ENCODE LZO,
	EnergySource3							    VARCHAR(100) ENCODE LZO,
	EnergySource4							    VARCHAR(100) ENCODE LZO,
	EnergySource5							    VARCHAR(100) ENCODE LZO,
	EnergySource6							    VARCHAR(100) ENCODE LZO,
	StartupSource1							    VARCHAR(100) ENCODE LZO,
	StartupSource2							    VARCHAR(100) ENCODE LZO,
	StartupSource3							    VARCHAR(100) ENCODE LZO,
	StartupSource4							    VARCHAR(100) ENCODE LZO,
	SolidFuelGasificationSystem				    VARCHAR(100) ENCODE LZO,
	CarbonCaptureTechnology					    VARCHAR(100) ENCODE LZO,
	Turbines_Inverters_orHydrokineticBuoys	    VARCHAR(100) ENCODE LZO,
	TimefromColdShutdowntoFullLoad			    VARCHAR(100) ENCODE LZO,
	FluidizedBedTechnology					    VARCHAR(100) ENCODE LZO,
	PulverizedCoalTechnology				    VARCHAR(100) ENCODE LZO,
	StokerTechnology						    VARCHAR(100) ENCODE LZO,
	OtherCombustionTechnology				    VARCHAR(100) ENCODE LZO,
	SubcriticalTechnology					    VARCHAR(100) ENCODE LZO,
	SupercriticalTechnology					    VARCHAR(100) ENCODE LZO,
	UltrasupercriticalTechnology			    VARCHAR(100) ENCODE LZO,
	CofireFuels								    VARCHAR(100) ENCODE LZO,
	SwitchBetweenOilandNaturalGas			    VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_1_generatorretcancelled
(
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Technology,
    PrimeMover,
    UnitCode,
    Ownership,
    DuctBurners,
    CanBypassHeatRecoverySteamGenerator,
    RTO_ISOLMPNodeDesignation,
    RTO_ISOLocationDesignation,
    NameplateCapacity_MW,
    NameplatePowerFactor,
    SummerCapacity_MW,
    WinterCapacity_MW,
    MinimumLoad_MW,
    UprateorDerateCompletedDuringYear,
    MonthUprateorDerateCompleted,
    YearUprateorDerateCompleted,
    Status,
    SynchronizedtoTransmissionGrid,
    OperatingMonth,
    OperatingYear,
    RetirementMonth,
    RetirementYear,
    AssociatedwithCombinedHeatandPowerSystem,
    SectorName,
    Sector,
    ToppingorBottoming,
    EnergySource1,
    EnergySource2,
    EnergySource3,
    EnergySource4,
    EnergySource5,
    EnergySource6,
    StartupSource1,
    StartupSource2,
    StartupSource3,
    StartupSource4,
    SolidFuelGasificationSystem,
    CarbonCaptureTechnology,
    Turbines_Inverters_orHydrokineticBuoys,
    TimefromColdShutdowntoFullLoad,
    FluidizedBedTechnology,
    PulverizedCoalTechnology,
    StokerTechnology,
    OtherCombustionTechnology,
    SubcriticalTechnology,
    SupercriticalTechnology,
    UltrasupercriticalTechnology,
    CofireFuels,
    SwitchBetweenOilandNaturalGas
)
SELECT
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Technology,
    PrimeMover,
    UnitCode,
    Ownership,
    DuctBurners,
    CanBypassHeatRecoverySteamGenerator,
    RTO_ISOLMPNodeDesignation,
    RTO_ISOLocationDesignation,
    CAST(CASE WHEN TRIM(NameplateCapacity_MW)='' THEN NULL ELSE NameplateCapacity_MW END AS FLOAT) AS NameplateCapacity_MW,
    NameplatePowerFactor,
    CAST(CASE WHEN TRIM(SummerCapacity_MW)='' THEN NULL ELSE SummerCapacity_MW END AS FLOAT) AS SummerCapacity_MW,
    CAST(CASE WHEN TRIM(WinterCapacity_MW)='' THEN NULL ELSE WinterCapacity_MW END AS FLOAT) AS WinterCapacity_MW,
    CAST(CASE WHEN TRIM(MinimumLoad_MW)='' THEN NULL ELSE MinimumLoad_MW END AS FLOAT) AS MinimumLoad_MW,
    UprateorDerateCompletedDuringYear,
    MonthUprateorDerateCompleted,
    YearUprateorDerateCompleted,
    Status,
    SynchronizedtoTransmissionGrid,
    OperatingMonth,
    OperatingYear,
    RetirementMonth,
    RetirementYear,
    AssociatedwithCombinedHeatandPowerSystem,
    SectorName,
    Sector,
    ToppingorBottoming,
    EnergySource1,
    EnergySource2,
    EnergySource3,
    EnergySource4,
    EnergySource5,
    EnergySource6,
    StartupSource1,
    StartupSource2,
    StartupSource3,
    StartupSource4,
    SolidFuelGasificationSystem,
    CarbonCaptureTechnology,
    Turbines_Inverters_orHydrokineticBuoys,
    TimefromColdShutdowntoFullLoad,
    FluidizedBedTechnology,
    PulverizedCoalTechnology,
    StokerTechnology,
    OtherCombustionTechnology,
    SubcriticalTechnology,
    SupercriticalTechnology,
    UltrasupercriticalTechnology,
    CofireFuels,
    SwitchBetweenOilandNaturalGas
FROM {schemaName}.{tableName}3_1_generatorretcancelled;





DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_2_windoperable CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_2_windoperable
(
    UtilityID                           INTEGER,
	UtilityName                         VARCHAR(100) ENCODE LZO,
	PlantCode                           VARCHAR(100) ENCODE LZO,
	PlantName                           VARCHAR(100) ENCODE LZO,
	State                               VARCHAR(100) ENCODE LZO,
	County                              VARCHAR(100) ENCODE LZO,
	GeneratorID                         VARCHAR(100) ENCODE LZO,
	Status                              VARCHAR(100) ENCODE LZO,
	Technology                          VARCHAR(100) ENCODE LZO,
	PrimeMover                          VARCHAR(100) ENCODE LZO,
	SectorName                          VARCHAR(100) ENCODE LZO,
	Sector                              VARCHAR(100) ENCODE LZO,
	NameplateCapacity_MW                FLOAT NULL,
	SummerCapacity_MW                   FLOAT NULL,
	WinterCapacity_MW                   FLOAT NULL,
	OperatingMonth                      VARCHAR(100) ENCODE LZO,
	OperatingYear                       VARCHAR(100) ENCODE LZO,
	NumberofTurbines                    VARCHAR(100) ENCODE LZO,
	PredominantTurbineManufacturer      VARCHAR(100) ENCODE LZO,
	PredominantTurbineModelNumber       VARCHAR(100) ENCODE LZO,
	DesignWindSpeed_mph                 VARCHAR(100) ENCODE LZO,
	WindQualityClass                    VARCHAR(100) ENCODE LZO,
	TurbineHubHeight_Feet               VARCHAR(100) ENCODE LZO,
	FAAObstacleNumber                   VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_2_windoperable
(
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    NameplateCapacity_MW,
    SummerCapacity_MW,
    WinterCapacity_MW,
    OperatingMonth,
    OperatingYear,
    NumberofTurbines,
    PredominantTurbineManufacturer,
    PredominantTurbineModelNumber,
    DesignWindSpeed_mph,
    WindQualityClass,
    TurbineHubHeight_Feet,
    FAAObstacleNumber
)
SELECT
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    CAST(CASE WHEN TRIM(NameplateCapacity_MW)='' THEN NULL ELSE NameplateCapacity_MW END AS FLOAT) AS NameplateCapacity_MW,
    CAST(CASE WHEN TRIM(SummerCapacity_MW)='' THEN NULL ELSE SummerCapacity_MW END AS FLOAT) AS SummerCapacity_MW,
    CAST(CASE WHEN TRIM(WinterCapacity_MW)='' THEN NULL ELSE WinterCapacity_MW END AS FLOAT) AS WinterCapacity_MW,
    OperatingMonth,
    OperatingYear,
    NumberofTurbines,
    PredominantTurbineManufacturer,
    PredominantTurbineModelNumber,
    DesignWindSpeed_mph,
    WindQualityClass,
    TurbineHubHeight_Feet,
    FAAObstacleNumber
FROM {schemaName}.{tableName}3_2_windoperable;





DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_2_windretcancelled CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_2_windretcancelled
(
    UtilityID                           INTEGER,
	UtilityName                         VARCHAR(100) ENCODE LZO,
	PlantCode                           VARCHAR(100) ENCODE LZO,
	PlantName                           VARCHAR(100) ENCODE LZO,
	State                               VARCHAR(100) ENCODE LZO,
	County                              VARCHAR(100) ENCODE LZO,
	GeneratorID                         VARCHAR(100) ENCODE LZO,
	Status                              VARCHAR(100) ENCODE LZO,
	Technology                          VARCHAR(100) ENCODE LZO,
	PrimeMover                          VARCHAR(100) ENCODE LZO,
	SectorName                          VARCHAR(100) ENCODE LZO,
	Sector                              VARCHAR(100) ENCODE LZO,
	NameplateCapacity_MW                FLOAT NULL,
	SummerCapacity_MW                   FLOAT NULL,
	WinterCapacity_MW                   FLOAT NULL,
	OperatingMonth                      VARCHAR(100) ENCODE LZO,
	OperatingYear                       VARCHAR(100) ENCODE LZO,
	NumberofTurbines                    VARCHAR(100) ENCODE LZO,
	PredominantTurbineManufacturer      VARCHAR(100) ENCODE LZO,
	PredominantTurbineModelNumber       VARCHAR(100) ENCODE LZO,
	DesignWindSpeed_mph                 VARCHAR(100) ENCODE LZO,
	WindQualityClass                    VARCHAR(100) ENCODE LZO,
	TurbineHubHeight_Feet               VARCHAR(100) ENCODE LZO,
	FAAObstacleNumber                   VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_2_windretcancelled
(
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    NameplateCapacity_MW,
    SummerCapacity_MW,
    WinterCapacity_MW,
    OperatingMonth,
    OperatingYear,
    NumberofTurbines,
    PredominantTurbineManufacturer,
    PredominantTurbineModelNumber,
    DesignWindSpeed_mph,
    WindQualityClass,
    TurbineHubHeight_Feet,
    FAAObstacleNumber    
)
SELECT
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    CAST(CASE WHEN TRIM(NameplateCapacity_MW)='' THEN NULL ELSE NameplateCapacity_MW END AS FLOAT) AS NameplateCapacity_MW,
    CAST(CASE WHEN TRIM(SummerCapacity_MW)='' THEN NULL ELSE SummerCapacity_MW END AS FLOAT) AS SummerCapacity_MW,
    CAST(CASE WHEN TRIM(WinterCapacity_MW)='' THEN NULL ELSE WinterCapacity_MW END AS FLOAT) AS WinterCapacity_MW,
    OperatingMonth,
    OperatingYear,
    NumberofTurbines,
    PredominantTurbineManufacturer,
    PredominantTurbineModelNumber,
    DesignWindSpeed_mph,
    WindQualityClass,
    TurbineHubHeight_Feet,
    FAAObstacleNumber
FROM {schemaName}.{tableName}3_2_windretcancelled;





DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_3_solaroperable CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_3_solaroperable
(
    UtilityID               INTEGER,
	UtilityName             VARCHAR(100) ENCODE LZO,
	PlantCode               VARCHAR(100) ENCODE LZO,
	PlantName               VARCHAR(100) ENCODE LZO,
	State                   VARCHAR(100) ENCODE LZO,
	County                  VARCHAR(100) ENCODE LZO,
	GeneratorID             VARCHAR(100) ENCODE LZO,
	Status                  VARCHAR(100) ENCODE LZO,
	Technology              VARCHAR(100) ENCODE LZO,
	PrimeMover              VARCHAR(100) ENCODE LZO,
	SectorName              VARCHAR(100) ENCODE LZO,
	Sector                  VARCHAR(100) ENCODE LZO,
	NameplateCapacity_MW    FLOAT NULL,
	SummerCapacity_MW       FLOAT NULL,
	WinterCapacity_MW       FLOAT NULL,
	OperatingMonth          VARCHAR(100) ENCODE LZO,
	OperatingYear           VARCHAR(100) ENCODE LZO,
	LensesMirrors          	VARCHAR(100) ENCODE LZO,
	SingleAxisTracking	    VARCHAR(100) ENCODE LZO,
	DualAxisTracking        VARCHAR(100) ENCODE LZO,
	FixedTilt               VARCHAR(100) ENCODE LZO,
	ParabolicTrough         VARCHAR(100) ENCODE LZO,
	LinearFresnel           VARCHAR(100) ENCODE LZO,
	PowerTower              VARCHAR(100) ENCODE LZO,
	DishEngine              VARCHAR(100) ENCODE LZO,
	OtherSolarTechnology    VARCHAR(100) ENCODE LZO,
	DCNetCapacity_MW        FLOAT NULL,
	CrystallineSilicon      VARCHAR(100) ENCODE LZO,
	ThinFilm_CdTe          	VARCHAR(100) ENCODE LZO,
	ThinFilm_ASi          	VARCHAR(100) ENCODE LZO,
	ThinFilm_CIGS          	VARCHAR(100) ENCODE LZO,
	ThinFilm_Other         	VARCHAR(100) ENCODE LZO,
	OtherMaterials          VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_3_solaroperable
(
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    NameplateCapacity_MW,
    SummerCapacity_MW,
    WinterCapacity_MW,
    OperatingMonth,
    OperatingYear,
    LensesMirrors,
    SingleAxisTracking,
    DualAxisTracking,
    FixedTilt,
    ParabolicTrough,
    LinearFresnel,
    PowerTower,
    DishEngine,
    OtherSolarTechnology,
    DCNetCapacity_MW,
    CrystallineSilicon,
    ThinFilm_CdTe,
    ThinFilm_ASi,
    ThinFilm_CIGS,
    ThinFilm_Other,
    OtherMaterials
)
SELECT
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    CAST(CASE WHEN TRIM(NameplateCapacity_MW)='' THEN NULL ELSE NameplateCapacity_MW END AS FLOAT) AS NameplateCapacity_MW,
    CAST(CASE WHEN TRIM(SummerCapacity_MW)='' THEN NULL ELSE SummerCapacity_MW END AS FLOAT) AS SummerCapacity_MW,
    CAST(CASE WHEN TRIM(WinterCapacity_MW)='' THEN NULL ELSE WinterCapacity_MW END AS FLOAT) AS WinterCapacity_MW,
    OperatingMonth,
    OperatingYear,
    LensesMirrors,
    SingleAxisTracking,
    DualAxisTracking,
    FixedTilt,
    ParabolicTrough,
    LinearFresnel,
    PowerTower,
    DishEngine,
    OtherSolarTechnology,    
    CAST(CASE WHEN TRIM(DCNetCapacity_MW)='' THEN NULL ELSE DCNetCapacity_MW END AS FLOAT) AS DCNetCapacity_MW,
    CrystallineSilicon,
    ThinFilm_CdTe,
    ThinFilm_ASi,
    ThinFilm_CIGS,
    ThinFilm_Other,
    OtherMaterials
FROM {schemaName}.{tableName}3_3_solaroperable;





DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_3_solarretcancelled CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_3_solarretcancelled
(
    UtilityID               INTEGER,
	UtilityName             VARCHAR(100) ENCODE LZO,
	PlantCode               VARCHAR(100) ENCODE LZO,
	PlantName               VARCHAR(100) ENCODE LZO,
	State                   VARCHAR(100) ENCODE LZO,
	County                  VARCHAR(100) ENCODE LZO,
	GeneratorID             VARCHAR(100) ENCODE LZO,
	Status                  VARCHAR(100) ENCODE LZO,
	Technology              VARCHAR(100) ENCODE LZO,
	PrimeMover              VARCHAR(100) ENCODE LZO,
	SectorName              VARCHAR(100) ENCODE LZO,
	Sector                  VARCHAR(100) ENCODE LZO,
	NameplateCapacity_MW    FLOAT NULL,
	SummerCapacity_MW       FLOAT NULL,
	WinterCapacity_MW       FLOAT NULL,
	OperatingMonth          VARCHAR(100) ENCODE LZO,
	OperatingYear           VARCHAR(100) ENCODE LZO,
	LensesMirrors           VARCHAR(100) ENCODE LZO,
	SingleAxisTracking      VARCHAR(100) ENCODE LZO,
	DualAxisTracking        VARCHAR(100) ENCODE LZO,
	FixedTilt               VARCHAR(100) ENCODE LZO,
	ParabolicTrough         VARCHAR(100) ENCODE LZO,
	LinearFresnel           VARCHAR(100) ENCODE LZO,
	PowerTower              VARCHAR(100) ENCODE LZO,
	DishEngine              VARCHAR(100) ENCODE LZO,
	OtherSolarTechnology    VARCHAR(100) ENCODE LZO,
	DCNetCapacity_MW        FLOAT NULL,
	CrystallineSilicon      VARCHAR(100) ENCODE LZO,
	ThinFilm_CdTe           VARCHAR(100) ENCODE LZO,
	ThinFilm_ASi            VARCHAR(100) ENCODE LZO,
	ThinFilm_CIGS           VARCHAR(100) ENCODE LZO,
	ThinFilm_Other          VARCHAR(100) ENCODE LZO,
	OtherMaterials          VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_3_solarretcancelled
(
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    NameplateCapacity_MW,
    SummerCapacity_MW,
    WinterCapacity_MW,
    OperatingMonth,
    OperatingYear,
    LensesMirrors,
    SingleAxisTracking,
    DualAxisTracking,
    FixedTilt,
    ParabolicTrough,
    LinearFresnel,
    PowerTower,
    DishEngine,
    OtherSolarTechnology,
    DCNetCapacity_MW,
    CrystallineSilicon,
    ThinFilm_CdTe,
    ThinFilm_ASi,
    ThinFilm_CIGS,
    ThinFilm_Other,
    OtherMaterials
)
SELECT
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    CAST(CASE WHEN TRIM(NameplateCapacity_MW)='' THEN NULL ELSE NameplateCapacity_MW END AS FLOAT) AS NameplateCapacity_MW,
    CAST(CASE WHEN TRIM(SummerCapacity_MW)='' THEN NULL ELSE SummerCapacity_MW END AS FLOAT) AS SummerCapacity_MW,
    CAST(CASE WHEN TRIM(WinterCapacity_MW)='' THEN NULL ELSE WinterCapacity_MW END AS FLOAT) AS WinterCapacity_MW,
    OperatingMonth,
    OperatingYear,
    LensesMirrors,
    SingleAxisTracking,
    DualAxisTracking,
    FixedTilt,
    ParabolicTrough,
    LinearFresnel,
    PowerTower,
    DishEngine,
    OtherSolarTechnology,
    CAST(CASE WHEN TRIM(DCNetCapacity_MW)='' THEN NULL ELSE DCNetCapacity_MW END AS FLOAT) AS DCNetCapacity_MW,
    CrystallineSilicon,
    ThinFilm_CdTe,
    ThinFilm_ASi,
    ThinFilm_CIGS,
    ThinFilm_Other,
    OtherMaterials
FROM {schemaName}.{tableName}3_3_solarretcancelled;





DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_4_multifueloperable CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_4_multifueloperable
(
    UtilityID                               INTEGER,
	UtilityName                             VARCHAR(100) ENCODE LZO,
	PlantCode                               VARCHAR(100) ENCODE LZO,
	PlantName                               VARCHAR(100) ENCODE LZO,
	State                                   VARCHAR(100) ENCODE LZO,
	County                                  VARCHAR(100) ENCODE LZO,
	GeneratorID                             VARCHAR(100) ENCODE LZO,
	Status                                  VARCHAR(100) ENCODE LZO,
	Technology                              VARCHAR(100) ENCODE LZO,
	PrimeMover                              VARCHAR(100) ENCODE LZO,
	SectorName                              VARCHAR(100) ENCODE LZO,
	Sector                                  VARCHAR(100) ENCODE LZO,
	NameplateCapacity_MW                    FLOAT NULL,
	SummerCapacity_MW                       FLOAT NULL,
	WinterCapacity_MW                       FLOAT NULL,
	EnergySource1                           VARCHAR(100) ENCODE LZO,
	EnergySource2                           VARCHAR(100) ENCODE LZO,
	CofireFuels                             VARCHAR(100) ENCODE LZO,
	CofireEnergySource1                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource2                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource3                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource4                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource5                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource6                     VARCHAR(100) ENCODE LZO,
	SwitchBetweenOilandNaturalGas           VARCHAR(100) ENCODE LZO,
	SwitchWhenOperating                     VARCHAR(100) ENCODE LZO,
	NetSummerCapacitywithNaturalGas_MW      FLOAT NULL,
	NetWinterCapacitywithNaturalGas_MW      FLOAT NULL,
	NetSummerCapacitywithOil_MW             FLOAT NULL,
	NetWinterCapacitywithOil_MW             FLOAT NULL,
	TimetoSwitchFromGastoOil                VARCHAR(100) ENCODE LZO,
	TimetoSwitchFromOiltoGas                VARCHAR(100) ENCODE LZO,
	FactorsthatLimitSwitching               VARCHAR(100) ENCODE LZO,
	StorageLimits                           VARCHAR(100) ENCODE LZO,
	AirPermitLimits                         VARCHAR(100) ENCODE LZO,
	OtherLimits                             VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_4_multifueloperable
(
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    NameplateCapacity_MW,
    SummerCapacity_MW,
    WinterCapacity_MW,
    EnergySource1,
    EnergySource2,
    CofireFuels,
    CofireEnergySource1,
    CofireEnergySource2,
    CofireEnergySource3,
    CofireEnergySource4,
    CofireEnergySource5,
    CofireEnergySource6,
    SwitchBetweenOilandNaturalGas,
    SwitchWhenOperating,
    NetSummerCapacitywithNaturalGas_MW,
    NetWinterCapacitywithNaturalGas_MW,
    NetSummerCapacitywithOil_MW,
    NetWinterCapacitywithOil_MW,
    TimetoSwitchFromGastoOil,
    TimetoSwitchFromOiltoGas,
    FactorsthatLimitSwitching,
    StorageLimits,
    AirPermitLimits,
    OtherLimits
)
SELECT
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    CAST(CASE WHEN TRIM(NameplateCapacity_MW)='' THEN NULL ELSE NameplateCapacity_MW END AS FLOAT) AS NameplateCapacity_MW,
    CAST(CASE WHEN TRIM(SummerCapacity_MW)='' THEN NULL ELSE SummerCapacity_MW END AS FLOAT) AS SummerCapacity_MW,
    CAST(CASE WHEN TRIM(WinterCapacity_MW)='' THEN NULL ELSE WinterCapacity_MW END AS FLOAT) AS WinterCapacity_MW,
    EnergySource1,
    EnergySource2,
    CofireFuels,
    CofireEnergySource1,
    CofireEnergySource2,
    CofireEnergySource3,
    CofireEnergySource4,
    CofireEnergySource5,
    CofireEnergySource6,
    SwitchBetweenOilandNaturalGas,
    SwitchWhenOperating,
    CAST(CASE WHEN TRIM(NetSummerCapacitywithNaturalGas_MW)='' THEN NULL ELSE NetSummerCapacitywithNaturalGas_MW END AS FLOAT) AS NetSummerCapacitywithNaturalGas_MW,
    CAST(CASE WHEN TRIM(NetWinterCapacitywithNaturalGas_MW)='' THEN NULL ELSE NetWinterCapacitywithNaturalGas_MW END AS FLOAT) AS NetWinterCapacitywithNaturalGas_MW,
    CAST(CASE WHEN TRIM(NetSummerCapacitywithOil_MW)='' THEN NULL ELSE NetSummerCapacitywithOil_MW END AS FLOAT) AS NetSummerCapacitywithOil_MW,
    CAST(CASE WHEN TRIM(NetWinterCapacitywithOil_MW)='' THEN NULL ELSE NetWinterCapacitywithOil_MW END AS FLOAT) AS NetWinterCapacitywithOil_MW,
    TimetoSwitchFromGastoOil,
    TimetoSwitchFromOiltoGas,
    FactorsthatLimitSwitching,
    StorageLimits,
    AirPermitLimits,
    OtherLimits
FROM {schemaName}.{tableName}3_4_multifueloperable;





DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_4_multifuelproposed CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_4_multifuelproposed
(
    UtilityID                       INTEGER,
	UtilityName                     VARCHAR(100) ENCODE LZO,
	PlantCode                       VARCHAR(100) ENCODE LZO,
	PlantName                       VARCHAR(100) ENCODE LZO,
	State                           VARCHAR(100) ENCODE LZO,
	County                          VARCHAR(100) ENCODE LZO,
	GeneratorID                     VARCHAR(100) ENCODE LZO,
	Status                          VARCHAR(100) ENCODE LZO,
	Technology                      VARCHAR(100) ENCODE LZO,
	PrimeMover                      VARCHAR(100) ENCODE LZO,
	SectorName                      VARCHAR(100) ENCODE LZO,
	Sector                          VARCHAR(100) ENCODE LZO,
	NameplateCapacity_MW            FLOAT NULL,
	SummerCapacity_MW               FLOAT NULL,
	WinterCapacity_MW               FLOAT NULL,
	EnergySource1                   VARCHAR(100) ENCODE LZO,
	EnergySource2                   VARCHAR(100) ENCODE LZO,
	CofireFuels                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource1             VARCHAR(100) ENCODE LZO,
	CofireEnergySource2             VARCHAR(100) ENCODE LZO,
	CofireEnergySource3             VARCHAR(100) ENCODE LZO,
	CofireEnergySource4             VARCHAR(100) ENCODE LZO,
	CofireEnergySource5             VARCHAR(100) ENCODE LZO,
	CofireEnergySource6             VARCHAR(100) ENCODE LZO,
	SwitchBetweenOilandNaturalGas   VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_4_multifuelproposed
(
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    NameplateCapacity_MW,
    SummerCapacity_MW,
    WinterCapacity_MW,
    EnergySource1,
    EnergySource2,
    CofireFuels,
    CofireEnergySource1,
    CofireEnergySource2,
    CofireEnergySource3,
    CofireEnergySource4,
    CofireEnergySource5,
    CofireEnergySource6,
    SwitchBetweenOilandNaturalGas
)
SELECT
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    CAST(CASE WHEN TRIM(NameplateCapacity_MW)='' THEN NULL ELSE NameplateCapacity_MW END AS FLOAT) AS NameplateCapacity_MW,
    CAST(CASE WHEN TRIM(SummerCapacity_MW)='' THEN NULL ELSE SummerCapacity_MW END AS FLOAT) AS SummerCapacity_MW,
    CAST(CASE WHEN TRIM(WinterCapacity_MW)='' THEN NULL ELSE WinterCapacity_MW END AS FLOAT) AS WinterCapacity_MW,
    EnergySource1,
    EnergySource2,
    CofireFuels,
    CofireEnergySource1,
    CofireEnergySource2,
    CofireEnergySource3,
    CofireEnergySource4,
    CofireEnergySource5,
    CofireEnergySource6,
    SwitchBetweenOilandNaturalGas
FROM {schemaName}.{tableName}3_4_multifuelproposed;





DROP TABLE IF EXISTS {schemaName}.{tableName}l2_3_4_multifuelretcancelled CASCADE;
CREATE TABLE {schemaName}.{tableName}l2_3_4_multifuelretcancelled
(
    UtilityID                               INTEGER,
	UtilityName                             VARCHAR(100) ENCODE LZO,
	PlantCode                               VARCHAR(100) ENCODE LZO,
	PlantName                               VARCHAR(100) ENCODE LZO,
	State                                   VARCHAR(100) ENCODE LZO,
	County                                  VARCHAR(100) ENCODE LZO,
	GeneratorID                             VARCHAR(100) ENCODE LZO,
	Status                                  VARCHAR(100) ENCODE LZO,
	Technology                              VARCHAR(100) ENCODE LZO,
	PrimeMover                              VARCHAR(100) ENCODE LZO,
	SectorName                              VARCHAR(100) ENCODE LZO,
	Sector                                  VARCHAR(100) ENCODE LZO,
	NameplateCapacity_MW                    FLOAT NULL,
	SummerCapacity_MW                       FLOAT NULL,
	WinterCapacity_MW                       FLOAT NULL,
	EnergySource1                           VARCHAR(100) ENCODE LZO,
	EnergySource2                           VARCHAR(100) ENCODE LZO,
	CofireFuels                             VARCHAR(100) ENCODE LZO,
	CofireEnergySource1                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource2                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource3                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource4                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource5                     VARCHAR(100) ENCODE LZO,
	CofireEnergySource6                     VARCHAR(100) ENCODE LZO,
	SwitchBetweenOilandNaturalGas           VARCHAR(100) ENCODE LZO,
	SwitchWhenOperating                     VARCHAR(100) ENCODE LZO,
	NetSummerCapacitywithNaturalGas_MW      FLOAT NULL,
	NetWinterCapacitywithNaturalGas_MW      FLOAT NULL,
	NetSummerCapacitywithOil_MW             FLOAT NULL,
	NetWinterCapacitywithOil_MW             FLOAT NULL,
	TimetoSwitchFromGastoOil                VARCHAR(100) ENCODE LZO,
	TimetoSwitchFromOiltoGas                VARCHAR(100) ENCODE LZO,
	FactorsthatLimitSwitching               VARCHAR(100) ENCODE LZO,
	StorageLimits                           VARCHAR(100) ENCODE LZO,
	AirPermitLimits                         VARCHAR(100) ENCODE LZO,
	OtherLimits                             VARCHAR(100) ENCODE LZO
);

INSERT INTO {schemaName}.{tableName}l2_3_4_multifuelretcancelled
(
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    NameplateCapacity_MW,
    SummerCapacity_MW,
    WinterCapacity_MW,
    EnergySource1,
    EnergySource2,
    CofireFuels,
    CofireEnergySource1,
    CofireEnergySource2,
    CofireEnergySource3,
    CofireEnergySource4,
    CofireEnergySource5,
    CofireEnergySource6,
    SwitchBetweenOilandNaturalGas,
    SwitchWhenOperating,
    NetSummerCapacitywithNaturalGas_MW,
    NetWinterCapacitywithNaturalGas_MW,
    NetSummerCapacitywithOil_MW,
    NetWinterCapacitywithOil_MW,
    TimetoSwitchFromGastoOil,
    TimetoSwitchFromOiltoGas,
    FactorsthatLimitSwitching,
    StorageLimits,
    AirPermitLimits,
    OtherLimits
)
SELECT
    UtilityID,
    UtilityName,
    PlantCode,
    PlantName,
    State,
    County,
    GeneratorID,
    Status,
    Technology,
    PrimeMover,
    SectorName,
    Sector,
    CAST(CASE WHEN TRIM(NameplateCapacity_MW)='' THEN NULL ELSE NameplateCapacity_MW END AS FLOAT) AS NameplateCapacity_MW,
    CAST(CASE WHEN TRIM(SummerCapacity_MW)='' THEN NULL ELSE SummerCapacity_MW END AS FLOAT) AS SummerCapacity_MW,
    CAST(CASE WHEN TRIM(WinterCapacity_MW)='' THEN NULL ELSE WinterCapacity_MW END AS FLOAT) AS WinterCapacity_MW,
    EnergySource1,
    EnergySource2,
    CofireFuels,
    CofireEnergySource1,
    CofireEnergySource2,
    CofireEnergySource3,
    CofireEnergySource4,
    CofireEnergySource5,
    CofireEnergySource6,
    SwitchBetweenOilandNaturalGas,
    SwitchWhenOperating,
    CAST(CASE WHEN TRIM(NetSummerCapacitywithNaturalGas_MW)='' THEN NULL ELSE NetSummerCapacitywithNaturalGas_MW END AS FLOAT) AS NetSummerCapacitywithNaturalGas_MW,
    CAST(CASE WHEN TRIM(NetWinterCapacitywithNaturalGas_MW)='' THEN NULL ELSE NetWinterCapacitywithNaturalGas_MW END AS FLOAT) AS NetWinterCapacitywithNaturalGas_MW,
    CAST(CASE WHEN TRIM(NetSummerCapacitywithOil_MW)='' THEN NULL ELSE NetSummerCapacitywithOil_MW END AS FLOAT) AS NetSummerCapacitywithOil_MW,
    CAST(CASE WHEN TRIM(NetWinterCapacitywithOil_MW)='' THEN NULL ELSE NetWinterCapacitywithOil_MW END AS FLOAT) AS NetWinterCapacitywithOil_MW,
    TimetoSwitchFromGastoOil,
    TimetoSwitchFromOiltoGas,
    FactorsthatLimitSwitching,
    StorageLimits,
    AirPermitLimits,
    OtherLimits
FROM {schemaName}.{tableName}3_4_multifuelretcancelled;

