DROP TABLE IF EXISTS {schemaName}.{tableName}1;
CREATE TABLE {schemaName}.{tableName}1
(
	RESPONDENT		BIGINT,
	RESPONDEN2		VARCHAR(60),
	RESPONDEN3		VARCHAR(10),
	STATUS		VARCHAR(10),
	FORM_TYPE		BIGINT,
	STATUS_DAT		VARCHAR(20),
	SORT_NAME		VARCHAR(10),
	PSWD_GEN		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}10;
CREATE TABLE {schemaName}.{tableName}10
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SUCCEEDING		BIGINT,
	AI_BGNYRBA		VARCHAR(20),
	AI_BGNYRB2		VARCHAR(100),
	AI_ACQ_YR_		VARCHAR(100),
	AI_ACQ_YR2		VARCHAR(100),
	AI_EPA_RET		VARCHAR(100),
	AI_EPA_RE2		VARCHAR(100),
	PX_USERDEF		VARCHAR(30),
	PX_USERDE2		VARCHAR(100),
	PX_USERDE3		VARCHAR(100),
	PX_USERDE4		VARCHAR(30),
	PX_USERDE5		VARCHAR(100),
	PX_USERDE6		VARCHAR(100),
	PX_USERDE7		VARCHAR(30),
	PX_USERDE8		VARCHAR(100),
	PX_USERDE9		VARCHAR(100),
	PX_USERD10		VARCHAR(30),
	PX_USERD11		VARCHAR(100),
	PX_USERD12		VARCHAR(100),
	PX_USERD13		VARCHAR(30),
	PX_USERD14		VARCHAR(100),
	PX_USERD15		VARCHAR(100),
	PX_USERD16		VARCHAR(30),
	PX_USERD17		VARCHAR(100),
	PX_USERD18		VARCHAR(100),
	PX_USERD19		VARCHAR(10),
	PX_USERD20		VARCHAR(100),
	PX_USERD21		VARCHAR(100),
	PX_TOTAL_N		VARCHAR(100),
	PX_TOTAL_A		VARCHAR(100),
	RDY_CHARGE		VARCHAR(100),
	RDY_CHARG2		VARCHAR(100),
	RDY_OTHER_		VARCHAR(100),
	RDY_OTHER2		VARCHAR(100),
	RDY_USERDE		VARCHAR(30),
	RDY_USERD2		VARCHAR(100),
	RDY_USERD3		VARCHAR(100),
	SX_USERDEF		VARCHAR(30),
	SX_USERDE2		VARCHAR(100),
	SX_USERDE3		VARCHAR(100),
	SX_USERDE4		VARCHAR(30),
	SX_USERDE5		VARCHAR(100),
	SX_USERDE6		VARCHAR(100),
	SX_USERDE7		VARCHAR(30),
	SX_USERDE8		VARCHAR(100),
	SX_USERDE9		VARCHAR(100),
	SX_USERD10		VARCHAR(30),
	SX_USERD11		VARCHAR(100),
	SX_USERD12		VARCHAR(100),
	SX_USERD13		VARCHAR(30),
	SX_USERD14		VARCHAR(100),
	SX_USERD15		VARCHAR(100),
	SX_USERD16		VARCHAR(20),
	SX_USERD17		VARCHAR(100),
	SX_USERD18		VARCHAR(100),
	SX_TOTAL_N		VARCHAR(100),
	SX_TOTAL_A		VARCHAR(100),
	SX_YRENDBA		VARCHAR(100),
	SX_YRENDB2		VARCHAR(100),
	SX_NET_ASS		VARCHAR(100),
	SX_NET_AS2		VARCHAR(100),
	SX_NET_OTH		VARCHAR(100),
	SX_NET_OT2		VARCHAR(100),
	SX_GAINS_N		VARCHAR(100),
	SX_GAINS_A		VARCHAR(100),
	SX_LOSSES_		VARCHAR(100),
	SX_LOSSES2		VARCHAR(100),
	AW_BGNYRBA		VARCHAR(100),
	AW_BGNYRB2		VARCHAR(100),
	AW_WITHHEL		VARCHAR(100),
	AW_WITHHE2		VARCHAR(100),
	AW_RETURNE		VARCHAR(100),
	AW_RETURN2		VARCHAR(100),
	AW_SALES_N		VARCHAR(100),
	AW_SALES_A		VARCHAR(100),
	AW_YRENDBA		VARCHAR(100),
	AW_YRENDB2		VARCHAR(100),
	AW_NET_ASS		VARCHAR(100),
	AW_NET_AS2		VARCHAR(100),
	AW_NET_OTH		VARCHAR(100),
	AW_NET_OT2		VARCHAR(100),
	AW_GAINS_N		VARCHAR(100),
	AW_GAINS_A		VARCHAR(100),
	AW_LOSSES_		VARCHAR(100),
	AW_LOSSES2		VARCHAR(100),
	SUCCEEDIN2		BIGINT,
	AI_BGNYRB3		BIGINT,
	AI_BGNYRB4		BIGINT,
	AI_ACQ_YR3		BIGINT,
	AI_ACQ_YR4		BIGINT,
	AI_EPA_RE3		BIGINT,
	AI_EPA_RE4		BIGINT,
	PX_USERD22		BIGINT,
	PX_USERD23		BIGINT,
	PX_USERD24		BIGINT,
	PX_USERD25		BIGINT,
	PX_USERD26		BIGINT,
	PX_USERD27		BIGINT,
	PX_USERD28		BIGINT,
	PX_USERD29		BIGINT,
	PX_USERD30		BIGINT,
	PX_USERD31		BIGINT,
	PX_USERD32		BIGINT,
	PX_USERD33		BIGINT,
	PX_USERD34		BIGINT,
	PX_USERD35		BIGINT,
	PX_USERD36		BIGINT,
	PX_USERD37		BIGINT,
	PX_USERD38		BIGINT,
	PX_USERD39		BIGINT,
	PX_USERD40		BIGINT,
	PX_USERD41		BIGINT,
	PX_USERD42		BIGINT,
	PX_TOTAL_2		BIGINT,
	PX_TOTAL_3		BIGINT,
	RDY_CHARG3		BIGINT,
	RDY_CHARG4		BIGINT,
	RDY_OTHER3		BIGINT,
	RDY_OTHER4		BIGINT,
	RDY_USERD4		BIGINT,
	RDY_USERD5		BIGINT,
	RDY_USERD6		BIGINT,
	SX_USERD19		BIGINT,
	SX_USERD20		BIGINT,
	SX_USERD21		BIGINT,
	SX_USERD22		BIGINT,
	SX_USERD23		BIGINT,
	SX_USERD24		BIGINT,
	SX_USERD25		BIGINT,
	SX_USERD26		BIGINT,
	SX_USERD27		BIGINT,
	SX_USERD28		BIGINT,
	SX_USERD29		BIGINT,
	SX_USERD30		BIGINT,
	SX_USERD31		BIGINT,
	SX_USERD32		BIGINT,
	SX_USERD33		BIGINT,
	SX_USERD34		BIGINT,
	SX_USERD35		BIGINT,
	SX_USERD36		BIGINT,
	SX_TOTAL_2		BIGINT,
	SX_TOTAL_3		BIGINT,
	SX_YRENDB3		BIGINT,
	SX_YRENDB4		BIGINT,
	SX_NET_AS3		BIGINT,
	SX_NET_AS4		BIGINT,
	SX_NET_OT3		BIGINT,
	SX_NET_OT4		BIGINT,
	SX_GAINS_2		BIGINT,
	SX_GAINS_3		BIGINT,
	SX_LOSSES3		BIGINT,
	SX_LOSSES4		BIGINT,
	AW_BGNYRB3		BIGINT,
	AW_BGNYRB4		BIGINT,
	AW_WITHHE3		BIGINT,
	AW_WITHHE4		BIGINT,
	AW_RETURN3		BIGINT,
	AW_RETURN4		BIGINT,
	AW_SALES_2		BIGINT,
	AW_SALES_3		BIGINT,
	AW_YRENDB3		BIGINT,
	AW_YRENDB4		BIGINT,
	AW_NET_AS3		BIGINT,
	AW_NET_AS4		BIGINT,
	AW_NET_OT3		BIGINT,
	AW_NET_OT4		BIGINT,
	AW_GAINS_2		BIGINT,
	AW_GAINS_3		BIGINT,
	AW_LOSSES3		BIGINT,
	AW_LOSSES4		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}106A_2009;
CREATE TABLE {schemaName}.{tableName}106A_2009
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCESSION_		VARCHAR(20),
	DOCUMENTDA		VARCHAR(20),
	DOCKETNO		VARCHAR(30),
	DESCRIPTIO		VARCHAR(60),
	RATESCHED		VARCHAR(60),
	RESP_FILE		BIGINT,
	ACCESSION2		BIGINT,
	DOCUMENTD2		BIGINT,
	DOCKETNO_F		BIGINT,
	DESCRIPTI2		BIGINT,
	RATESCHED_		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}106B_2009;
CREATE TABLE {schemaName}.{tableName}106B_2009
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PAGENOS		VARCHAR(20),
	SCHEDULE		VARCHAR(60),
	COLUMN1		VARCHAR(10),
	LINENO		VARCHAR(30),
	PAGENOS_F		BIGINT,
	SCHEDULE_F		BIGINT,
	COLUMN_F		BIGINT,
	LINENO_F		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}106_2009;
CREATE TABLE {schemaName}.{tableName}106_2009
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SCHED_TARI		VARCHAR(60),
	FERC_PROCE		VARCHAR(60),
	FORMULA_RA		BIGINT,
	SCHED_TAR2		BIGINT,
	FERC_PROC2		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}11;
CREATE TABLE {schemaName}.{tableName}11
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	BEGIN_YR_B		VARCHAR(10),
	END_YR_BAL		VARCHAR(10),
	BEGIN_YR_2		BIGINT,
	END_YR_BA2		BIGINT,
	REPORT_PRD		BIGINT,
	END_QTR_BA		BIGINT,
	PRI_YR_Q4_		BIGINT,
	END_QTR_B2		BIGINT,
	PRI_YR_Q42		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}12;
CREATE TABLE {schemaName}.{tableName}12
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CLSSERS_ST		VARCHAR(50),
	NUM_SHR_AT		BIGINT,
	PAR_STATED		VARCHAR(100),
	CALL_PRC_E		VARCHAR(100),
	SHR_OSTD_B		BIGINT,
	AMT_OSTD_B		BIGINT,
	SHR_REACQ_		BIGINT,
	COST_REACQ		BIGINT,
	SHR_SINKIN		BIGINT,
	AMT_SINKIN		BIGINT,
	CLSSERS_S2		BIGINT,
	NUM_SHR_A2		BIGINT,
	PAR_STATE2		BIGINT,
	CALL_PRC_2		BIGINT,
	SHR_OSTD_2		BIGINT,
	AMT_OSTD_2		BIGINT,
	SHR_REACQ2		BIGINT,
	COST_REAC2		BIGINT,
	SHR_SINKI2		BIGINT,
	AMT_SINKI2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}13;
CREATE TABLE {schemaName}.{tableName}13
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESCRIPTIO		VARCHAR(80),
	AMOUNTS			BIGINT,
	DESCRIPTI2		BIGINT,
	AMOUNTS_F		BIGINT,
	PREV_AMOUN		BIGINT,
	PREV_AMOU2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}14;
CREATE TABLE {schemaName}.{tableName}14
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	NOTES		VARCHAR(21120),
	NOTES_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}15;
CREATE TABLE {schemaName}.{tableName}15
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	BEGIN_YR_B		VARCHAR(10),
	END_YR_BAL		VARCHAR(10),
	BEGIN_YR_2		BIGINT,
	END_YR_BA2		BIGINT,
	REPORT_PRD		BIGINT,
	END_QTR_BA		BIGINT,
	PRI_YR_Q4_		BIGINT,
	END_QTR_B2		BIGINT,
	PRI_YR_Q42		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}16;
CREATE TABLE {schemaName}.{tableName}16
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	DESCRIPTIO		VARCHAR(10),
	TOT_AMOUNT		VARCHAR(10),
	DESCRIPTI2		VARCHAR(10),
	TOT_AMOUN2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}17;
CREATE TABLE {schemaName}.{tableName}17
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CO_CNTRL_I		VARCHAR(2080),
	CO_CNTRL_2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}18;
CREATE TABLE {schemaName}.{tableName}18
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DIRECTOR_N		VARCHAR(70),
	PRNCPL_CO_		VARCHAR(70),
	DIRECTOR_2		BIGINT,
	PRNCPL_CO2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}19;
CREATE TABLE {schemaName}.{tableName}19
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	STK_CLS_EX		VARCHAR(100),
	YR_END_BAL		BIGINT,
	STK_CLS_E2		BIGINT,
	YR_END_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}2;
CREATE TABLE {schemaName}.{tableName}2
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	AMRTZD_CHR		VARCHAR(1340),
	AMRTZD_CH2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}20;
CREATE TABLE {schemaName}.{tableName}20
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	ACCT_NAM_I		VARCHAR(10),
	NUM_SHR		VARCHAR(10),
	AMOUNT		VARCHAR(10),
	ACCT_NAM_2		VARCHAR(10),
	NUM_SHR_F		VARCHAR(10),
	AMOUNT_F		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}208_ELC_DEP;
CREATE TABLE {schemaName}.{tableName}208_ELC_DEP
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PLNT_END_Q		BIGINT,
	ACCUM_END_		BIGINT,
	PLNT_END_2		BIGINT,
	ACCUM_END2		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}21;
CREATE TABLE {schemaName}.{tableName}21
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DEPR_EXPN		BIGINT,
	DEPR_ASSET		BIGINT,
	LIMTERM_EL		BIGINT,
	OTHR_ELC_P		BIGINT,
	TOTAL		BIGINT,
	DEPR_EXPN_		BIGINT,
	DEPR_ASSE2		BIGINT,
	LIMTERM_E2		BIGINT,
	OTHR_ELC_2		BIGINT,
	TOTAL_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}22;
CREATE TABLE {schemaName}.{tableName}22
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	STK_CLS_SE		VARCHAR(10),
	YR_END_BAL		VARCHAR(10),
	STK_CLS_S2		VARCHAR(10),
	YR_END_BA2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}23;
CREATE TABLE {schemaName}.{tableName}23
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCT_NUM		VARCHAR(30),
	DEPR_PLNT_		BIGINT,
	EST_AVG_SR		VARCHAR(100),
	NET_SALVAG		VARCHAR(100),
	APPLY_DEPR		VARCHAR(100),
	MRTLTY_CRV		VARCHAR(20),
	AVG_REMAIN		VARCHAR(100),
	ACCT_NUM_F		BIGINT,
	DEPR_PLNT2		BIGINT,
	EST_AVG_S2		BIGINT,
	NET_SALVA2		BIGINT,
	APPLY_DEP2		BIGINT,
	MRTLTY_CR2		BIGINT,
	AVG_REMAI2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}231_TRN_STDYCST;
CREATE TABLE {schemaName}.{tableName}231_TRN_STDYCST
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	DESCRIPTIO		VARCHAR(40),
	PRD_COSTS		BIGINT,
	ACCT_CHRGD		VARCHAR(30),
	REIMB_RCVD		BIGINT,
	ACCT_CREDI		VARCHAR(30),
	ROW_PRVLG		VARCHAR(10),
	DESCRIPTI2		BIGINT,
	PRD_COSTS_		BIGINT,
	ACCT_CHRG2		BIGINT,
	REIMB_RCV2		BIGINT,
	ACCT_CRED2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}24;
CREATE TABLE {schemaName}.{tableName}24
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ERG_SRC_MW		VARCHAR(100),
	ERG_DISP_M		VARCHAR(20),
	ERG_SRC_M2		BIGINT,
	ERG_DISP_2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}25;
CREATE TABLE {schemaName}.{tableName}25
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCT_DSC		VARCHAR(60),
	REV_AMT_CR		BIGINT,
	REV_AMT_PR		BIGINT,
	MWH_SOLD_C		BIGINT,
	MWH_SOLD_P		BIGINT,
	AVG_CSTMR_		BIGINT,
	AVG_CSTMR2		BIGINT,
	ACCT_DSC_F		BIGINT,
	REV_AMT_C2		BIGINT,
	REV_AMT_P2		BIGINT,
	MWH_SOLD_2		BIGINT,
	MWH_SOLD_3		BIGINT,
	AVG_CSTMR3		BIGINT,
	AVG_CSTMR4		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}26;
CREATE TABLE {schemaName}.{tableName}26
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	UNBILLED_R		BIGINT,
	UNBILLED_2		BIGINT,
	UNBILLED_3		BIGINT,
	UNBILLED_4		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}27;
CREATE TABLE {schemaName}.{tableName}27
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CRNT_YR_AM		BIGINT,
	PREV_YR_AM		BIGINT,
	CRNT_YR_A2		BIGINT,
	PREV_YR_A2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}28;
CREATE TABLE {schemaName}.{tableName}28
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	NUMBER_WAT		VARCHAR(10),
	NUMBER_LIN		VARCHAR(10),
	TOT_CAPACI		VARCHAR(10),
	NUMBER_WA2		VARCHAR(10),
	NUMBER_LI2		VARCHAR(10),
	TOT_CAPAC2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}29;
CREATE TABLE {schemaName}.{tableName}29
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	AMOUNT		VARCHAR(10),
	ACTUAL_EXP		VARCHAR(10),
	AMOUNT_F		VARCHAR(10),
	ACTUAL_EX2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}3;
CREATE TABLE {schemaName}.{tableName}3
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ITEM		VARCHAR(40),
	TOTAL_CDE		BIGINT,
	ELECTRIC_P		BIGINT,
	FUTURE_PLA		BIGINT,
	LEASED_PLA		BIGINT,
	ITEM_F		BIGINT,
	TOTAL_CDE_		BIGINT,
	ELECTRIC_2		BIGINT,
	FUTURE_PL2		BIGINT,
	LEASED_PL2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}30;
CREATE TABLE {schemaName}.{tableName}30
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	ADDITIONS		VARCHAR(10),
	RETIREMENT		VARCHAR(10),
	ADJUSTMENT		VARCHAR(10),
	YR_END_BAL		VARCHAR(10),
	ACTUAL_COS		VARCHAR(10),
	ADDITIONS_		VARCHAR(10),
	RETIREMEN2		VARCHAR(10),
	ADJUSTMEN2		VARCHAR(10),
	YR_END_BA2		VARCHAR(10),
	ACTUAL_CO2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}31;
CREATE TABLE {schemaName}.{tableName}31
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PLANT_NAME		VARCHAR(30),
	FUEL		VARCHAR(20),
	FUEL_UNIT		VARCHAR(20),
	FUEL_QUANT		BIGINT,
	FUEL_AVG_H		BIGINT,
	FUEL_COST_		VARCHAR(100),
	FUEL_COST2		VARCHAR(100),
	FUEL_COST3		VARCHAR(100),
	FUEL_COST4		VARCHAR(100),
	FUEL_GENER		VARCHAR(100),
	FUEL_F		BIGINT,
	FUEL_UNIT_		BIGINT,
	FUEL_QUAN2		BIGINT,
	FUEL_AVG_2		BIGINT,
	FUEL_COST5		BIGINT,
	FUEL_COST6		BIGINT,
	FUEL_COST7		BIGINT,
	FUEL_COST8		BIGINT,
	FUEL_GENE2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}32;
CREATE TABLE {schemaName}.{tableName}32
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CORPORATE_		VARCHAR(310),
	INC_INFO		VARCHAR(300),
	RECV_TRUST		VARCHAR(80),
	UTILITY_CL		VARCHAR(1200),
	PRNCPL_ACC		VARCHAR(10),
	PRNCPL_AC2		VARCHAR(20),
	CORPORATE2		BIGINT,
	INC_INFO_F		BIGINT,
	RECV_TRUS2		BIGINT,
	UTILITY_C2		BIGINT,
	PRNCPL_AC3		BIGINT,
	PRNCPL_AC4		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}324_ELC_EXPNS;
CREATE TABLE {schemaName}.{tableName}324_ELC_EXPNS
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	YR_TO_DATE		BIGINT,
	YR_TO_DAT2		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}325_ELC_CUST;
CREATE TABLE {schemaName}.{tableName}325_ELC_CUST
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	YR_TO_DATE		BIGINT,
	YR_TO_DAT2		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}33;
CREATE TABLE {schemaName}.{tableName}33
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PLANT_NAME		VARCHAR(50),
	YR_CONSTRU		VARCHAR(100),
	CAPACITY_R		VARCHAR(100),
	NET_DEMAND		VARCHAR(100),
	NET_GENERA		BIGINT,
	PLANT_COST		BIGINT,
	PLANT_COS2		BIGINT,
	OPERATION		BIGINT,
	EXPNS_FUEL		BIGINT,
	EXPNS_MAIN		BIGINT,
	KIND_OF_FU		VARCHAR(20),
	FUEL_COST		BIGINT,
	PLANT_NAM2		BIGINT,
	YR_CONSTR2		BIGINT,
	CAPACITY_2		BIGINT,
	NET_DEMAN2		BIGINT,
	NET_GENER2		BIGINT,
	PLANT_COS3		BIGINT,
	PLANT_COS4		BIGINT,
	OPERATION_		BIGINT,
	EXPNS_FUE2		BIGINT,
	EXPNS_MAI2		BIGINT,
	KIND_OF_F2		BIGINT,
	FUEL_COST_		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}331_TRANSISO;
CREATE TABLE {schemaName}.{tableName}331_TRANSISO
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PYMT_RECV		VARCHAR(50),
	STAT_CLASS		VARCHAR(10),
	FERC_SCHED		VARCHAR(30),
	TOT_REV_BY		VARCHAR(100),
	TOT_REV		VARCHAR(100),
	PYMT_RECV_		BIGINT,
	STAT_CLAS2		BIGINT,
	FERC_SCHE2		BIGINT,
	TOT_REV_B2		BIGINT,
	TOT_REV_F		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}338_DEP_DEPL;
CREATE TABLE {schemaName}.{tableName}338_DEP_DEPL
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DEP_EXP		BIGINT,
	DEP_EXP_AS		BIGINT,
	AMORT_ELEC		BIGINT,
	AMORT_OTHE		BIGINT,
	AMT_TOTAL		BIGINT,
	DEP_EXP_F		BIGINT,
	DEP_EXP_A2		BIGINT,
	AMORT_ELE2		BIGINT,
	AMORT_OTH2		BIGINT,
	AMT_TOTAL_		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}34;
CREATE TABLE {schemaName}.{tableName}34
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	IMPORTANT_		VARCHAR(10),
	IMPORTANT2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}35;
CREATE TABLE {schemaName}.{tableName}35
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CY_OTHER_T		BIGINT,
	PREV_YR_TO		BIGINT,
	CY_OTHER_2		BIGINT,
	PREV_YR_T2		BIGINT,
	CURR_3_MON		BIGINT,
	PRIOR_3_MO		BIGINT,
	CURR_3_MO2		BIGINT,
	PRIOR_3_M2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}36;
CREATE TABLE {schemaName}.{tableName}36
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CURRENT_YR		BIGINT,
	PREVIOUS_Y		BIGINT,
	CY_ELCTRC_		BIGINT,
	PREV_YR_EL		BIGINT,
	CY_GAS_TOT		BIGINT,
	PREV_YR_GA		BIGINT,
	CY_OTHER_T		BIGINT,
	PREV_YR_OT		BIGINT,
	CY_OTHER_2		BIGINT,
	PREV_YR_O2		BIGINT,
	CY_OTHER_3		BIGINT,
	PREV_YR_O3		BIGINT,
	CY_OTHER_4		BIGINT,
	PREV_YR_O4		BIGINT,
	CURRENT_Y2		BIGINT,
	PREVIOUS_2		BIGINT,
	CY_ELCTRC2		BIGINT,
	PREV_YR_E2		BIGINT,
	CY_GAS_TO2		BIGINT,
	PREV_YR_G2		BIGINT,
	CY_OTHER_5		BIGINT,
	PREV_YR_O5		BIGINT,
	CY_OTHER_6		BIGINT,
	PREV_YR_O6		BIGINT,
	CY_OTHER_7		BIGINT,
	PREV_YR_O7		BIGINT,
	CY_OTHER_8		BIGINT,
	PREV_YR_O8		BIGINT,
	CURR_3_MON		BIGINT,
	PRIOR_3_MO		BIGINT,
	CURR_3_MO2		BIGINT,
	PRIOR_3_M2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}37;
CREATE TABLE {schemaName}.{tableName}37
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESCRIPTIO		VARCHAR(60),
	AMOUNT		BIGINT,
	DESCRIPTI2		BIGINT,
	AMOUNT_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}38;
CREATE TABLE {schemaName}.{tableName}38
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DFRRD_DEBI		VARCHAR(40),
	BEGIN_YR_B		BIGINT,
	DEBITS			BIGINT,
	ACCT_CHRG_		VARCHAR(10),
	AMOUNT_CR		BIGINT,
	YR_END_BAL		BIGINT,
	DFRRD_DEB2		BIGINT,
	BEGIN_YR_2		BIGINT,
	DEBITS_F		BIGINT,
	ACCT_CHRG2		BIGINT,
	AMOUNT_CR_		BIGINT,
	YR_END_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}39;
CREATE TABLE {schemaName}.{tableName}39
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SYSTEM_NAM		VARCHAR(70),
	TOT_MTHLY_		BIGINT,
	MTHLY_SALE		BIGINT,
	MEGAWATTS		BIGINT,
	DAY_OF_MON		BIGINT,
	HOUR		VARCHAR(10),
	SYSTEM_NA2		BIGINT,
	TOT_MTHLY2		BIGINT,
	MTHLY_SAL2		BIGINT,
	MEGAWATTS_		BIGINT,
	DAY_OF_MO2		BIGINT,
	HOUR_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}397_ISORTO_STL;
CREATE TABLE {schemaName}.{tableName}397_ISORTO_STL
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESC_ITEM		VARCHAR(50),
	BAL_END_Q1		VARCHAR(100),
	BAL_END_Q2		VARCHAR(100),
	BAL_END_Q3		VARCHAR(100),
	BAL_END_Q4		VARCHAR(100),
	DESC_ITEM_		BIGINT,
	BAL_END_Q5		BIGINT,
	BAL_END_Q6		BIGINT,
	BAL_END_Q7		BIGINT,
	BAL_END_Q8		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}398_ANCL_PS;
CREATE TABLE {schemaName}.{tableName}398_ANCL_PS
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	PURCH_NUM_		BIGINT,
	PURCH_UNIT		VARCHAR(20),
	PURCH_DOLL		BIGINT,
	SOLD_NUM_U		BIGINT,
	SOLD_UNIT		VARCHAR(20),
	SOLD_DOLLA		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PURCH_NUM2		BIGINT,
	PURCH_UNI2		BIGINT,
	PURCH_DOL2		BIGINT,
	SOLD_NUM_2		BIGINT,
	SOLD_UNIT_		BIGINT,
	SOLD_DOLL2		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}399_MTH_PEAK;
CREATE TABLE {schemaName}.{tableName}399_MTH_PEAK
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SYSTEM_NAM		VARCHAR(80),
	TOT_MTH_EN		BIGINT,
	MTH_LOSS		BIGINT,
	MEGAWATTS		BIGINT,
	DAY_OF_MTH		BIGINT,
	HOUR_OF_DA		BIGINT,
	SYSTEM_NA2		BIGINT,
	TOT_MTH_E2		BIGINT,
	MTH_LOSS_F		BIGINT,
	MEGAWATTS_		BIGINT,
	DAY_OF_MT2		BIGINT,
	HOUR_OF_D2		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}4;
CREATE TABLE {schemaName}.{tableName}4
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCT_SUBDI		VARCHAR(20),
	BEGIN_YR_B		BIGINT,
	ACCT_DEFER		VARCHAR(20),
	AMT_DEFERR		BIGINT,
	CRNT_ALLOC		VARCHAR(20),
	CRNT_ALLO2		BIGINT,
	ADJUSTMENT		BIGINT,
	YR_END_BAL		BIGINT,
	ALLOC_INCM		VARCHAR(20),
	ACCT_SUBD2		BIGINT,
	BEGIN_YR_2		BIGINT,
	ACCT_DEFE2		BIGINT,
	AMT_DEFER2		BIGINT,
	CRNT_ALLO3		BIGINT,
	CRNT_ALLO4		BIGINT,
	ADJUSTMEN2		BIGINT,
	YR_END_BA2		BIGINT,
	ALLOC_INC2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}40;
CREATE TABLE {schemaName}.{tableName}40
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCOUNT		VARCHAR(40),
	BEGIN_YR_B		BIGINT,
	YR_END_BAL		BIGINT,
	DEPT_MATER		VARCHAR(20),
	ACCOUNT_F		BIGINT,
	BEGIN_YR_2		BIGINT,
	YR_END_BA2		BIGINT,
	DEPT_MATE2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}400A_ISO_PEAK;
CREATE TABLE {schemaName}.{tableName}400A_ISO_PEAK
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SYSTEM_NAM		VARCHAR(50),
	MTH_PEAK		BIGINT,
	DAY_OF_MTH		BIGINT,
	HOUR_OF_DA		BIGINT,
	IMPORTS		BIGINT,
	EXPORTS		BIGINT,
	THROUGH_OU		BIGINT,
	NET_SERV		BIGINT,
	PTP_SERV		BIGINT,
	TOT_USE		BIGINT,
	SYSTEM_NA2		BIGINT,
	MTH_PEAK_F		BIGINT,
	DAY_OF_MT2		BIGINT,
	HOUR_OF_D2		BIGINT,
	IMPORTS_F		BIGINT,
	EXPORTS_F		BIGINT,
	THROUGH_O2		BIGINT,
	NET_SERV_F		BIGINT,
	PTP_SERV_F		BIGINT,
	TOT_USE_F		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}400_SYS_PEAK;
CREATE TABLE {schemaName}.{tableName}400_SYS_PEAK
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SYSTEM_NAM		VARCHAR(50),
	MTH_PEAK		BIGINT,
	DAY_OF_MTH		BIGINT,
	HOUR_OF_DA		BIGINT,
	FIRM_FOR_S		BIGINT,
	FIRM_FOR_O		BIGINT,
	PTP_RES		BIGINT,
	OTHER_LT_F		BIGINT,
	SHORT_PTP_		BIGINT,
	OTHER_SERV		BIGINT,
	SYSTEM_NA2		BIGINT,
	MTH_PEAK_F		BIGINT,
	DAY_OF_MT2		BIGINT,
	HOUR_OF_D2		BIGINT,
	FIRM_FOR_2		BIGINT,
	FIRM_FOR_3		BIGINT,
	PTP_RES_F		BIGINT,
	OTHER_LT_2		BIGINT,
	SHORT_PTP2		BIGINT,
	OTHER_SER2		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}41;
CREATE TABLE {schemaName}.{tableName}41
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	PYRL_PER_E		VARCHAR(10),
	TOT_RGLR_F		VARCHAR(10),
	TOT_PTE_TE		VARCHAR(10),
	TOT_EMP		VARCHAR(10),
	PYRL_PER_2		VARCHAR(10),
	TOT_RGLR_2		VARCHAR(10),
	TOT_PTE_T2		VARCHAR(10),
	TOT_EMP_F		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}42;
CREATE TABLE {schemaName}.{tableName}42
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	DSC_AND_LO		VARCHAR(10),
	BEGIN_YR_B		VARCHAR(10),
	PRCHS_SALE		VARCHAR(10),
	YR_END_BAL		VARCHAR(10),
	DSC_AND_L2		VARCHAR(10),
	BEGIN_YR_2		VARCHAR(10),
	PRCHS_SAL2		VARCHAR(10),
	YR_END_BA2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}429_TRANS_AFF;
CREATE TABLE {schemaName}.{tableName}429_TRANS_AFF
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESC_GOOD_		VARCHAR(60),
	NAME_COMP		VARCHAR(60),
	ACCT_CORC		VARCHAR(30),
	AMT_CORC		BIGINT,
	DESC_GOOD2		BIGINT,
	NAME_COMP_		BIGINT,
	ACCT_CORC_		BIGINT,
	AMT_CORC_F		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}43;
CREATE TABLE {schemaName}.{tableName}43
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	NOTE_FIN_S		VARCHAR(10),
	NOTE_FIN_2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}44;
CREATE TABLE {schemaName}.{tableName}44
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	BEGIN_YR_B		BIGINT,
	YRCHG_ADDI		BIGINT,
	YRCHG_AMRT		BIGINT,
	YRCHG_OTHR		BIGINT,
	YR_END_BAL		BIGINT,
	BEGIN_YR_2		BIGINT,
	YRCHG_ADD2		BIGINT,
	YRCHG_AMR2		BIGINT,
	YRCHG_OTH2		BIGINT,
	YR_END_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}45;
CREATE TABLE {schemaName}.{tableName}45
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	OFFICER_TI		VARCHAR(60),
	OFFICER_NA		VARCHAR(40),
	OFFICER_SA		BIGINT,
	OFFICER_T2		BIGINT,
	OFFICER_N2		BIGINT,
	OFFICER_S2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}46;
CREATE TABLE {schemaName}.{tableName}46
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	OTHR_DFR_C		VARCHAR(40),
	BEGIN_YR_B		BIGINT,
	CONTRA_ACC		VARCHAR(20),
	AMOUNT_DR		BIGINT,
	CREDITS			BIGINT,
	YR_END_BAL		BIGINT,
	OTHR_DFR_2		BIGINT,
	BEGIN_YR_2		BIGINT,
	CONTRA_AC2		BIGINT,
	AMOUNT_DR_		BIGINT,
	CREDITS_F		BIGINT,
	YR_END_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}47;
CREATE TABLE {schemaName}.{tableName}47
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ITEM			VARCHAR(80),
	AMOUNT			BIGINT,
	ITEM_F			BIGINT,
	AMOUNT_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}48;
CREATE TABLE {schemaName}.{tableName}48
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DSC_PURP_A		VARCHAR(60),
	DEBITS			BIGINT,
	ACCT_CHRG_		VARCHAR(20),
	AMOUNT_CR		BIGINT,
	YR_END_BAL		BIGINT,
	DSC_PURP_2		BIGINT,
	DEBITS_F		BIGINT,
	ACCT_CHRG2		BIGINT,
	AMOUNT_CR_		BIGINT,
	YR_END_BA2		BIGINT,
	BEG_YR_BAL		BIGINT,
	BEG_YR_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}49;
CREATE TABLE {schemaName}.{tableName}49
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DSC_PURP		VARCHAR(50),
	DR_ACCT_NU		VARCHAR(20),
	DR_AMOUNT		BIGINT,
	CREDITS		BIGINT,
	END_YR_BAL		BIGINT,
	DSC_PURP_F		BIGINT,
	DR_ACCT_N2		BIGINT,
	DR_AMOUNT_		BIGINT,
	CREDITS_F		BIGINT,
	END_YR_BA2		BIGINT,
	BEG_YR_BAL		BIGINT,
	BEG_YR_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}5;
CREATE TABLE {schemaName}.{tableName}5
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCT_SUBDI		VARCHAR(70),
	BEGIN_YR_B		BIGINT,
	YR_END_BAL		BIGINT,
	ACCT_SUBD2		BIGINT,
	BEGIN_YR_2		BIGINT,
	YR_END_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}50;
CREATE TABLE {schemaName}.{tableName}50
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	NOTE		VARCHAR(10),
	AMOUNT		VARCHAR(10),
	CAPITALIZA		VARCHAR(10),
	COST_RATE		VARCHAR(10),
	GROSS		VARCHAR(10),
	RATE		VARCHAR(10),
	RATE_BORRO		VARCHAR(10),
	RATE_OTHER		VARCHAR(10),
	NOTE_F		VARCHAR(10),
	AMOUNT_F		VARCHAR(10),
	CAPITALIZ2		VARCHAR(10),
	COST_RATE_		VARCHAR(10),
	GROSS_F		VARCHAR(10),
	RATE_F		VARCHAR(10),
	RATE_BORR2		VARCHAR(10),
	RATE_OTHE2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}51;
CREATE TABLE {schemaName}.{tableName}51
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	ITEM		VARCHAR(10),
	AMOUNT		VARCHAR(10),
	ACCOUNT		VARCHAR(10),
	ITEM_F		VARCHAR(10),
	AMOUNT_F		VARCHAR(10),
	ACCOUNT_F		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}52;
CREATE TABLE {schemaName}.{tableName}52
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	BEGIN_YR_B		BIGINT,
	ADDITION		BIGINT,
	RETIREMENT		BIGINT,
	ADJUSTMENT		BIGINT,
	TRANSFERS		BIGINT,
	YR_END_BAL		BIGINT,
	BEGIN_YR_2		BIGINT,
	ADDITION_F		BIGINT,
	RETIREMEN2		BIGINT,
	ADJUSTMEN2		BIGINT,
	TRANSFERS_		BIGINT,
	YR_END_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}53;
CREATE TABLE {schemaName}.{tableName}53
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PROJECT_NO		BIGINT,
	PLANT_NAME		VARCHAR(30),
	PLANT_KIND		VARCHAR(20),
	YR_CONST		VARCHAR(100),
	YR_INSTALL		VARCHAR(100),
	TOT_CAPACI		VARCHAR(100),
	PEAK_DEMAN		BIGINT,
	PLANT_HOUR		BIGINT,
	PLANT_CAPA		BIGINT,
	AVG_NUM_OF		BIGINT,
	NET_GENERA		BIGINT,
	ENERGY_USE		BIGINT,
	NET_LOAD		BIGINT,
	COST_LAND		BIGINT,
	COST_STRUC		BIGINT,
	COST_FACIL		BIGINT,
	COST_WHEEL		BIGINT,
	COST_ELECT		BIGINT,
	COST_MISC_		BIGINT,
	COST_ROADS		BIGINT,
	ASSET_RETI		BIGINT,
	COST_OF_PL		BIGINT,
	COST_PER_K		VARCHAR(100),
	EXPNS_OPER		BIGINT,
	EXPNS_WATE		BIGINT,
	EXPNS_PUMP		BIGINT,
	EXPNS_ELEC		BIGINT,
	EXPNS_MISC		BIGINT,
	EXPNS_RENT		BIGINT,
	EXPNS_ENGN		BIGINT,
	EXPNS_STRU		BIGINT,
	EXPNS_DAMS		BIGINT,
	EXPNS_PLAN		BIGINT,
	EXPNS_MIS2		BIGINT,
	EXPNS_PROD		BIGINT,
	PUMPING_EX		BIGINT,
	TOT_PRDCTN		BIGINT,
	EXPNS_KWH		VARCHAR(100),
	PROJECT_N2		BIGINT,
	PLANT_NAM2		BIGINT,
	PLANT_KIN2		BIGINT,
	YR_CONST_F		BIGINT,
	YR_INSTAL2		BIGINT,
	TOT_CAPAC2		BIGINT,
	PEAK_DEMA2		BIGINT,
	PLANT_HOU2		BIGINT,
	PLANT_CAP2		BIGINT,
	AVG_NUM_O2		BIGINT,
	NET_GENER2		BIGINT,
	ENERGY_US2		BIGINT,
	NET_LOAD_F		BIGINT,
	COST_LAND_		BIGINT,
	COST_STRU2		BIGINT,
	COST_FACI2		BIGINT,
	COST_WHEE2		BIGINT,
	COST_ELEC2		BIGINT,
	COST_MISC2		BIGINT,
	COST_ROAD2		BIGINT,
	ASSET_RET2		BIGINT,
	COST_OF_P2		BIGINT,
	COST_PER_2		BIGINT,
	EXPNS_OPE2		BIGINT,
	EXPNS_WAT2		BIGINT,
	EXPNS_PUM2		BIGINT,
	EXPNS_ELE2		BIGINT,
	EXPNS_MIS3		BIGINT,
	EXPNS_REN2		BIGINT,
	EXPNS_ENG2		BIGINT,
	EXPNS_STR2		BIGINT,
	EXPNS_DAM2		BIGINT,
	EXPNS_PLA2		BIGINT,
	EXPNS_MIS4		BIGINT,
	EXPNS_PRO2		BIGINT,
	PUMPING_E2		BIGINT,
	TOT_PRDCT2		BIGINT,
	EXPNS_KWH_		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}54;
CREATE TABLE {schemaName}.{tableName}54
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ATHRTY_CO_		VARCHAR(40),
	STTSTCL_CL		VARCHAR(10),
	RTSCHED_TR		VARCHAR(20),
	AVGMTH_BIL		VARCHAR(20),
	AVGMTH_NCP		VARCHAR(20),
	AVGMTH_CP_		VARCHAR(20),
	MWH_PURCHA		BIGINT,
	MWH_RECV		BIGINT,
	MWH_DELVD		BIGINT,
	DMND_CHARG		BIGINT,
	ERG_CHARGE		BIGINT,
	OTHR_CHARG		BIGINT,
	SETTLEMENT		BIGINT,
	ATHRTY_CO2		BIGINT,
	STTSTCL_C2		BIGINT,
	RTSCHED_T2		BIGINT,
	AVGMTH_BI2		BIGINT,
	AVGMTH_NC2		BIGINT,
	AVGMTH_CP2		BIGINT,
	MWH_PURCH2		BIGINT,
	MWH_RECV_F		BIGINT,
	MWH_DELVD_		BIGINT,
	DMND_CHAR2		BIGINT,
	ERG_CHARG2		BIGINT,
	OTHR_CHAR2		BIGINT,
	SETTLEMEN2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}55;
CREATE TABLE {schemaName}.{tableName}55
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PARTICULAR		VARCHAR(80),
	AMOUNT			BIGINT,
	PARTICULA2		BIGINT,
	AMOUNT_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}56;
CREATE TABLE {schemaName}.{tableName}56
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESCRIPTIO		VARCHAR(50),
	ASSESS_REG		BIGINT,
	UTILITY_EX		BIGINT,
	TOT_EXPN_T		BIGINT,
	DFRRD_ACCT		BIGINT,
	DEPARTMENT		VARCHAR(20),
	ACCT_NBR		VARCHAR(10),
	AMT_CHRG_C		BIGINT,
	DFRRD_ACC2		BIGINT,
	CONTRA_ACC		VARCHAR(20),
	AMT_AMRTZD		BIGINT,
	DFRRD_ACC3		BIGINT,
	DESCRIPTI2		BIGINT,
	ASSESS_RE2		BIGINT,
	UTILITY_E2		BIGINT,
	TOT_EXPN_2		BIGINT,
	DFRRD_ACC4		BIGINT,
	DEPARTMEN2		BIGINT,
	ACCT_NBR_F		BIGINT,
	AMT_CHRG_2		BIGINT,
	DFRRD_ACC5		BIGINT,
	CONTRA_AC2		BIGINT,
	AMT_AMRTZ2		BIGINT,
	DFRRD_ACC6		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}57;
CREATE TABLE {schemaName}.{tableName}57
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CO_CNTRL_N		VARCHAR(50),
	BUSN_TYP		VARCHAR(30),
	PRCNT_STK_		VARCHAR(30),
	FOOTNOTE_R		VARCHAR(30),
	CO_CNTRL_2		BIGINT,
	BUSN_TYP_F		BIGINT,
	PRCNT_STK2		BIGINT,
	FOOTNOTE_2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}58;
CREATE TABLE {schemaName}.{tableName}58
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ITEM		VARCHAR(80),
	PRMRY_ACCO		VARCHAR(20),
	AMOUNT			BIGINT,
	ITEM_F			BIGINT,
	PRMRY_ACC2		BIGINT,
	AMOUNT_F		BIGINT,
	PREV_BALAN		BIGINT,
	PREV_BALA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}59;
CREATE TABLE {schemaName}.{tableName}59
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CLASSIFICA		VARCHAR(50),
	DESCRIPTIO		VARCHAR(80),
	COST_INCR_		BIGINT,
	COST_INCR2		BIGINT,
	ACCOUNT		VARCHAR(10),
	AMOUNT		BIGINT,
	UNAMRTZD_A		BIGINT,
	CLASSIFIC2		BIGINT,
	DESCRIPTI2		BIGINT,
	COST_INCR3		BIGINT,
	COST_INCR4		BIGINT,
	ACCOUNT_F		BIGINT,
	AMOUNT_F		BIGINT,
	UNAMRTZD_2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}6;
CREATE TABLE {schemaName}.{tableName}6
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	NOTES		VARCHAR(4300),
	NOTES_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}60;
CREATE TABLE {schemaName}.{tableName}60
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ			BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SCHED_NUM_		VARCHAR(40),
	MWH_SOLD		BIGINT,
	REVENUE			BIGINT,
	AVG_NUM_CS		BIGINT,
	KWH_SALE_C		BIGINT,
	REVENUE_KW		VARCHAR(100),
	SCHED_NUM2		BIGINT,
	MWH_SOLD_F		BIGINT,
	REVENUE_F		BIGINT,
	AVG_NUM_C2		BIGINT,
	KWH_SALE_2		BIGINT,
	REVENUE_K2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}61;
CREATE TABLE {schemaName}.{tableName}61
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	COMPANY_NA		VARCHAR(40),
	STTSTCL_CL		VARCHAR(10),
	FERC_RT_SC		VARCHAR(20),
	AVG_MTHLY_		VARCHAR(10),
	AVG_MTHLY2		VARCHAR(10),
	AVG_MTHLY3		VARCHAR(10),
	MWH_SOLD		BIGINT,
	DEMAND_CHA		BIGINT,
	ENERGY_CHA		BIGINT,
	OTHER_CHAR		BIGINT,
	TOT_REVENU		BIGINT,
	COMPANY_N2		BIGINT,
	STTSTCL_C2		BIGINT,
	FERC_RT_S2		BIGINT,
	AVG_MTHLY4		BIGINT,
	AVG_MTHLY5		BIGINT,
	AVG_MTHLY6		BIGINT,
	MWH_SOLD_F		BIGINT,
	DEMAND_CH2		BIGINT,
	ENERGY_CH2		BIGINT,
	OTHER_CHA2		BIGINT,
	TOT_REVEN2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}62;
CREATE TABLE {schemaName}.{tableName}62
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	TOTAL_COST		BIGINT,
	BEGIN_YR_T		BIGINT,
	EQTY_ERNG_		BIGINT,
	YR_REVENUE		BIGINT,
	YR_END_TOT		BIGINT,
	GAIN_LOSS_		BIGINT,
	TOTAL_COS2		BIGINT,
	BEGIN_YR_2		BIGINT,
	EQTY_ERNG2		BIGINT,
	YR_REVENU2		BIGINT,
	YR_END_TO2		BIGINT,
	GAIN_LOSS2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}63;
CREATE TABLE {schemaName}.{tableName}63
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	REMARKS		VARCHAR(20),
	STK_HLD_IN		VARCHAR(100),
	REMARKS_F		BIGINT,
	STK_HLD_I2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}64;
CREATE TABLE {schemaName}.{tableName}64
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	STOCK_BOOK		VARCHAR(10),
	VOTE_CAST_		VARCHAR(10),
	PROXY_VOTE		VARCHAR(10),
	MEETING_IN		VARCHAR(10),
	VOTES_AS_O		VARCHAR(10),
	HOLDER_INF		VARCHAR(10),
	VOTE_TOTAL		VARCHAR(10),
	CMMN_STOCK		VARCHAR(10),
	PREFERRED_		VARCHAR(10),
	OTHER_TOTA		VARCHAR(10),
	STOCK_BOO2		VARCHAR(10),
	VOTE_CAST2		VARCHAR(10),
	PROXY_VOT2		VARCHAR(10),
	MEETING_I2		VARCHAR(10),
	VOTES_AS_2		VARCHAR(10),
	HOLDER_IN2		VARCHAR(10),
	VOTE_TOTA2		VARCHAR(10),
	CMMN_STOC2		VARCHAR(10),
	PREFERRED2		VARCHAR(10),
	OTHER_TOT2		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}65;
CREATE TABLE {schemaName}.{tableName}65
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CLASSIFICA		VARCHAR(70),
	DRCT_PYRL_		BIGINT,
	ALLOC_OF_P		BIGINT,
	TOTAL		BIGINT,
	CLASSIFIC2		BIGINT,
	DRCT_PYRL2		BIGINT,
	ALLOC_OF_2		BIGINT,
	TOTAL_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}66;
CREATE TABLE {schemaName}.{tableName}66
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SUBSTN_LOC		VARCHAR(60),
	SUBSTN_CHA		VARCHAR(30),
	PRMRY_VOLT		VARCHAR(100),
	SCNDRY_VOL		VARCHAR(100),
	TRTRY_VOLT		VARCHAR(100),
	SUBSTN_CAP		BIGINT,
	NO_TRANSFO		BIGINT,
	NO_SPARES		BIGINT,
	EQUIP_TYPE		VARCHAR(30),
	NO_OF_UNIT		BIGINT,
	TOTAL_CAPA		BIGINT,
	SUBSTN_LO2		BIGINT,
	SUBSTN_CH2		BIGINT,
	PRMRY_VOL2		BIGINT,
	SCNDRY_VO2		BIGINT,
	TRTRY_VOL2		BIGINT,
	SUBSTN_CA2		BIGINT,
	NO_TRANSF2		BIGINT,
	NO_SPARES_		BIGINT,
	EQUIP_TYP2		BIGINT,
	NO_OF_UNI2		BIGINT,
	TOTAL_CAP2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}67;
CREATE TABLE {schemaName}.{tableName}67
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	TAX_KIND		VARCHAR(30),
	TAX_ACCRD_		BIGINT,
	PRPD_TAX_B		BIGINT,
	TAX_CHRG_D		BIGINT,
	TAX_PAID_D		BIGINT,
	ADJUSTMENT		BIGINT,
	TAX_ACCRD2		BIGINT,
	PRPD_TAX_E		BIGINT,
	ELECTRIC		BIGINT,
	XTRAORDNRY		BIGINT,
	RETERNG_AD		BIGINT,
	OTHER		BIGINT,
	TAX_KIND_F		BIGINT,
	TAX_ACCRD3		BIGINT,
	PRPD_TAX_2		BIGINT,
	TAX_CHRG_2		BIGINT,
	TAX_PAID_2		BIGINT,
	ADJUSTMEN2		BIGINT,
	TAX_ACCRD4		BIGINT,
	PRPD_TAX_3		BIGINT,
	ELECTRIC_F		BIGINT,
	XTRAORDNR2		BIGINT,
	RETERNG_A2		BIGINT,
	OTHER_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}68;
CREATE TABLE {schemaName}.{tableName}68
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	COST_DSC		VARCHAR(40),
	CHRG_AMT_T		BIGINT,
	RECOGNIZED		BIGINT,
	ACCT_WRTTN		VARCHAR(10),
	AMT_WRTTN_		BIGINT,
	YR_END_BAL		BIGINT,
	COST_DSC_F		BIGINT,
	CHRG_AMT_2		BIGINT,
	RECOGNIZE2		BIGINT,
	ACCT_WRTT2		BIGINT,
	AMT_WRTTN2		BIGINT,
	YR_END_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}69;
CREATE TABLE {schemaName}.{tableName}69
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	OTHER		VARCHAR(20),
	SERVICE_PL		BIGINT,
	PROPUNDR_C		BIGINT,
	PLNT_PRCHS		BIGINT,
	CMPLT_CONS		BIGINT,
	XPRMNT_PLN		BIGINT,
	IN_SRVC_TO		BIGINT,
	LEASED_TO_		BIGINT,
	HELD_FTRE_		BIGINT,
	CONST_WRK_		BIGINT,
	ACQSTN_ADJ		BIGINT,
	TOT_UTLTY_		BIGINT,
	ACCUM_PRVS		BIGINT,
	NET_UTLTY_		BIGINT,
	IN_SRVCE_D		BIGINT,
	AMRTZD_DPL		BIGINT,
	AMRTZD_UGR		BIGINT,
	AMRTZ_UTLT		BIGINT,
	TOT_IN_SER		BIGINT,
	LEASED_OTH		BIGINT,
	AMRTZ_DPLT		BIGINT,
	TOT_LEASED		BIGINT,
	DEPR_FTRE_		BIGINT,
	AMORTIZATI		BIGINT,
	TOTAL_FTRE		BIGINT,
	ABNDN_LEAS		BIGINT,
	AMRTZPLNT_		BIGINT,
	TOT_ACCUM_		BIGINT,
	OTHER_F		BIGINT,
	SERVICE_P2		BIGINT,
	PROPUNDR_2		BIGINT,
	PLNT_PRCH2		BIGINT,
	CMPLT_CON2		BIGINT,
	XPRMNT_PL2		BIGINT,
	IN_SRVC_T2		BIGINT,
	LEASED_TO2		BIGINT,
	HELD_FTRE2		BIGINT,
	CONST_WRK2		BIGINT,
	ACQSTN_AD2		BIGINT,
	TOT_UTLTY2		BIGINT,
	ACCUM_PRV2		BIGINT,
	NET_UTLTY2		BIGINT,
	IN_SRVCE_2		BIGINT,
	AMRTZD_DP2		BIGINT,
	AMRTZD_UG2		BIGINT,
	AMRTZ_UTL2		BIGINT,
	TOT_IN_SE2		BIGINT,
	LEASED_OT2		BIGINT,
	AMRTZ_DPL2		BIGINT,
	TOT_LEASE2		BIGINT,
	DEPR_FTRE2		BIGINT,
	AMORTIZAT2		BIGINT,
	TOTAL_FTR2		BIGINT,
	ABNDN_LEA2		BIGINT,
	AMRTZPLNT2		BIGINT,
	TOT_ACCUM2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}7;
CREATE TABLE {schemaName}.{tableName}7
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCT_DSC		VARCHAR(40),
	BGN_YR_BAL		BIGINT,
	CHG_YR_DR_		BIGINT,
	CHG_YR_CR_		BIGINT,
	CHG_YR_DR2		BIGINT,
	CHG_YR_CR2		BIGINT,
	DR_ADJ_ACC		VARCHAR(10),
	DR_ADJ_AMT		BIGINT,
	CR_ADJ_ACC		VARCHAR(10),
	CR_ADJ_AMT		BIGINT,
	END_YR_BAL		BIGINT,
	ACCT_DSC_F		BIGINT,
	BGN_YR_BA2		BIGINT,
	CHG_YR_DR3		BIGINT,
	CHG_YR_CR3		BIGINT,
	CHG_YR_DR4		BIGINT,
	CHG_YR_CR4		BIGINT,
	DR_ADJ_AC2		BIGINT,
	DR_ADJ_AM2		BIGINT,
	CR_ADJ_AC2		BIGINT,
	CR_ADJ_AM2		BIGINT,
	END_YR_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}70;
CREATE TABLE {schemaName}.{tableName}70
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESCRIPTIO		VARCHAR(100),
	WORK_IN_PR		BIGINT,
	DESCRIPTI2		BIGINT,
	WORK_IN_P2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}71;
CREATE TABLE {schemaName}.{tableName}71
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESIGNATIO		VARCHAR(40),
	DESIGNATI2		VARCHAR(30),
	LINE_LENGT		VARCHAR(100),
	STRUCTURE_		VARCHAR(20),
	STRUCTURE2		VARCHAR(100),
	CRCT_PRESE		BIGINT,
	CRCT_ULTIM		BIGINT,
	CNDCTR_SIZ		VARCHAR(100),
	CNDCTR_SPE		VARCHAR(10),
	CNDCTR_CON		VARCHAR(20),
	VOLTAGE		BIGINT,
	COST_LAND		BIGINT,
	COST_POLES		BIGINT,
	COST_CNDCT		BIGINT,
	ASSET_RETI		BIGINT,
	COST_TOTAL		BIGINT,
	DESIGNATI3		BIGINT,
	DESIGNATI4		BIGINT,
	LINE_LENG2		BIGINT,
	STRUCTURE3		BIGINT,
	STRUCTURE4		BIGINT,
	CRCT_PRES2		BIGINT,
	CRCT_ULTI2		BIGINT,
	CNDCTR_SI2		BIGINT,
	CNDCTR_SP2		BIGINT,
	CNDCTR_CO2		BIGINT,
	VOLTAGE_F		BIGINT,
	COST_LAND_		BIGINT,
	COST_POLE2		BIGINT,
	COST_CNDC2		BIGINT,
	ASSET_RET2		BIGINT,
	COST_TOTA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}72;
CREATE TABLE {schemaName}.{tableName}72
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ATHRTY_CO_		VARCHAR(30),
	MWH_RECV		BIGINT,
	MWH_DELVD		BIGINT,
	DEMAND_CHR		BIGINT,
	ERG_CHRG		BIGINT,
	OTHR_CHRG		BIGINT,
	XMSSN_TOT_		BIGINT,
	ATHRTY_CO2		BIGINT,
	MWH_RECV_F		BIGINT,
	MWH_DELVD_		BIGINT,
	DEMAND_CH2		BIGINT,
	ERG_CHRG_F		BIGINT,
	OTHR_CHRG_		BIGINT,
	XMSSN_TOT2		BIGINT,
	STAT_CLASS		VARCHAR(10),
	STAT_CLAS2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}73;
CREATE TABLE {schemaName}.{tableName}73
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PAYMENT_BY		VARCHAR(50),
	ERG_RECV_F		VARCHAR(40),
	ERG_DELVD_		VARCHAR(40),
	STTSTCL_CL		VARCHAR(10),
	RTSCHED_TR		VARCHAR(20),
	RECEIPT_PO		VARCHAR(30),
	DELIVERY_P		VARCHAR(30),
	BILLING_DE		BIGINT,
	MWH_RECV		BIGINT,
	MWH_DELVD		BIGINT,
	DMND_CHARG		BIGINT,
	ERG_CHARGE		BIGINT,
	OTHR_CHARG		BIGINT,
	TOT_REVENU		BIGINT,
	PAYMENT_B2		BIGINT,
	ERG_RECV_2		BIGINT,
	ERG_DELVD2		BIGINT,
	STTSTCL_C2		BIGINT,
	RTSCHED_T2		BIGINT,
	RECEIPT_P2		BIGINT,
	DELIVERY_2		BIGINT,
	BILLING_D2		BIGINT,
	MWH_RECV_F		BIGINT,
	MWH_DELVD_		BIGINT,
	DMND_CHAR2		BIGINT,
	ERG_CHARG2		BIGINT,
	OTHR_CHAR2		BIGINT,
	TOT_REVEN2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}74;
CREATE TABLE {schemaName}.{tableName}74
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESIGNATIO		VARCHAR(30),
	DESIGNATI2		VARCHAR(30),
	VOLTAGE_OP		VARCHAR(100),
	DESIGNED_V		VARCHAR(100),
	STRUCTURE		VARCHAR(20),
	LENGTH_DSG		VARCHAR(100),
	LENGTH_ANO		VARCHAR(100),
	NUM_OF_CIR		BIGINT,
	CONDUCTOR_		VARCHAR(20),
	COST_LAND		BIGINT,
	COST_OTHER		BIGINT,
	COST_TOTAL		BIGINT,
	EXPNS_OPER		BIGINT,
	EXPNS_MAIN		BIGINT,
	EXPNS_RENT		BIGINT,
	EXPNS_TOTA		BIGINT,
	DESIGNATI3		BIGINT,
	DESIGNATI4		BIGINT,
	VOLTAGE_O2		BIGINT,
	DESIGNED_2		BIGINT,
	STRUCTURE_		BIGINT,
	LENGTH_DS2		BIGINT,
	LENGTH_AN2		BIGINT,
	NUM_OF_CI2		BIGINT,
	CONDUCTOR2		BIGINT,
	COST_LAND_		BIGINT,
	COST_OTHE2		BIGINT,
	COST_TOTA2		BIGINT,
	EXPNS_OPE2		BIGINT,
	EXPNS_MAI2		BIGINT,
	EXPNS_REN2		BIGINT,
	EXPNS_TOT2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}75;
CREATE TABLE {schemaName}.{tableName}75
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	LOSS_DSC		VARCHAR(40),
	AMT_LOSS_T		BIGINT,
	RECOGNIZED		BIGINT,
	ACCT_WRTTN		VARCHAR(10),
	AMT_WRTTN_		BIGINT,
	YR_END_BAL		BIGINT,
	LOSS_DSC_F		BIGINT,
	AMT_LOSS_2		BIGINT,
	RECOGNIZE2		BIGINT,
	ACCT_WRTT2		BIGINT,
	AMT_WRTTN2		BIGINT,
	YR_END_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}76;
CREATE TABLE {schemaName}.{tableName}76
(
	CODE		BIGINT,
	DESCRIPTIO		VARCHAR(80)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}77;
CREATE TABLE {schemaName}.{tableName}77
(
	SCHED_TABL		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SCHED_LITE		VARCHAR(10),
	SCHED_STAT		VARCHAR(10),
	SCHED_CHG_		VARCHAR(10),
	TURNED_SCH		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}78;
CREATE TABLE {schemaName}.{tableName}78
(
	SERIAL_NUM		VARCHAR(10),
	EVENT_DATE		VARCHAR(10),
	PROGRAM_ID		VARCHAR(10),
	EVENT_CODE		VARCHAR(10),
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	USER_ID		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}79;
CREATE TABLE {schemaName}.{tableName}79
(
	SCHED_TABL		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	COLUMN_NAM		VARCHAR(10),
	COL_LITERA		VARCHAR(10),
	COL_STATUS		VARCHAR(10),
	COL_CHG_YR		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}8;
CREATE TABLE {schemaName}.{tableName}8
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCT_DSC		VARCHAR(40),
	BGN_YR_BAL		BIGINT,
	CHG_YR_DR_		BIGINT,
	CHG_YR_CR_		BIGINT,
	CHG_YR_DR2		BIGINT,
	CHG_YR_CR2		BIGINT,
	DR_ADJ_ACC		VARCHAR(10),
	DR_ADJ_AMT		BIGINT,
	CR_ADJ_ACC		VARCHAR(10),
	CR_ADJ_AMT		BIGINT,
	END_YR_BAL		BIGINT,
	ACCT_DSC_F		BIGINT,
	BGN_YR_BA2		BIGINT,
	CHG_YR_DR3		BIGINT,
	CHG_YR_CR3		BIGINT,
	CHG_YR_DR4		BIGINT,
	CHG_YR_CR4		BIGINT,
	DR_ADJ_AC2		BIGINT,
	DR_ADJ_AM2		BIGINT,
	CR_ADJ_AC2		BIGINT,
	CR_ADJ_AM2		BIGINT,
	END_YR_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}80;
CREATE TABLE {schemaName}.{tableName}80
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	FILE_NAME		VARCHAR(10),
	FILE_TYPE		VARCHAR(10),
	DB_TABLE_N		VARCHAR(10),
	COLUMN_NAM		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}81;
CREATE TABLE {schemaName}.{tableName}81
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SCHED_TABL		VARCHAR(10),
	ROW_SEQ		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}82;
CREATE TABLE {schemaName}.{tableName}82
(
	SERIAL_NUM		VARCHAR(10),
	DATE_TIME		VARCHAR(10),
	PROGRAM_ID		VARCHAR(10),
	CURR_FUNCT		VARCHAR(10),
	SQL_CODE		VARCHAR(10),
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	USERID		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}83;
CREATE TABLE {schemaName}.{tableName}83
(
	UNIQUE_NUM		BIGINT,
	RESPDNT_LA		BIGINT,
	FN_LAST_NU		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}84;
CREATE TABLE {schemaName}.{tableName}84
(
	SCHED_TABL		VARCHAR(20),
	REPORT_YEA		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_LITERA		VARCHAR(80),
	ROW_STATUS		VARCHAR(10),
	ROW_CHG_YR		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}85;
CREATE TABLE {schemaName}.{tableName}85
(
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ROW_NUMBER1		VARCHAR(10),
	ROW_SEQ		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	PAGE_NUMBE		VARCHAR(10),
	ITEM_NUMBE		VARCHAR(10),
	COLUMN_NUM		VARCHAR(10),
	COMMENTS		VARCHAR(10),
	PAGE_NUMB2		VARCHAR(10),
	ITEM_NUMB2		VARCHAR(10),
	COLUMN_NU2		VARCHAR(10),
	COMMENTS_F		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}86;
CREATE TABLE {schemaName}.{tableName}86
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PROJECT_NO		BIGINT,
	PLANT_NAME		VARCHAR(20),
	PLANT_KIND		VARCHAR(30),
	PLANT_CONS		VARCHAR(30),
	YR_CONST		VARCHAR(100),
	YR_INSTALL		VARCHAR(100),
	TOT_CAPACI		VARCHAR(100),
	PEAK_DEMAN		BIGINT,
	PLANT_HOUR		BIGINT,
	FAVORABLE_		BIGINT,
	ADVERSE_CO		BIGINT,
	AVG_NUM_OF		BIGINT,
	NET_GENERA		BIGINT,
	COST_OF_LA		BIGINT,
	COST_STRUC		BIGINT,
	COST_FACIL		BIGINT,
	COST_EQUIP		BIGINT,
	COST_ROADS		BIGINT,
	COST_PLANT		BIGINT,
	COST_PER_K		VARCHAR(100),
	EXPNS_OPER		BIGINT,
	EXPNS_WATE		BIGINT,
	EXPNS_HYDR		BIGINT,
	EXPNS_ELEC		BIGINT,
	EXPNS_GENE		BIGINT,
	EXPNS_RENT		BIGINT,
	EXPNS_ENGN		BIGINT,
	EXPNS_STRU		BIGINT,
	EXPNS_DAMS		BIGINT,
	EXPNS_PLAN		BIGINT,
	EXPNS_MISC		BIGINT,
	EXPNS_TOTA		BIGINT,
	EXPNS_KWH		VARCHAR(100),
	PROJECT_N2		BIGINT,
	PLANT_NAM2		BIGINT,
	PLANT_KIN2		BIGINT,
	PLANT_CON2		BIGINT,
	YR_CONST_F		BIGINT,
	YR_INSTAL2		BIGINT,
	TOT_CAPAC2		BIGINT,
	PEAK_DEMA2		BIGINT,
	PLANT_HOU2		BIGINT,
	FAVORABLE2		BIGINT,
	ADVERSE_C2		BIGINT,
	AVG_NUM_O2		BIGINT,
	NET_GENER2		BIGINT,
	COST_OF_L2		BIGINT,
	COST_STRU2		BIGINT,
	COST_FACI2		BIGINT,
	COST_EQUI2		BIGINT,
	COST_ROAD2		BIGINT,
	COST_PLAN2		BIGINT,
	COST_PER_2		BIGINT,
	EXPNS_OPE2		BIGINT,
	EXPNS_WAT2		BIGINT,
	EXPNS_HYD2		BIGINT,
	EXPNS_ELE2		BIGINT,
	EXPNS_GEN2		BIGINT,
	EXPNS_REN2		BIGINT,
	EXPNS_ENG2		BIGINT,
	EXPNS_STR2		BIGINT,
	EXPNS_DAM2		BIGINT,
	EXPNS_PLA2		BIGINT,
	EXPNS_MIS2		BIGINT,
	EXPNS_TOT2		BIGINT,
	EXPNS_KWH_		BIGINT,
	ASSET_RETI		BIGINT,
	ASSET_RET2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}87;
CREATE TABLE {schemaName}.{tableName}87
(
	FN_ID		VARCHAR(10),
	RESPONDENT		VARCHAR(10),
	REPORT_YEA		VARCHAR(10),
	ROW_PRVLG		VARCHAR(10),
	PAGE_NUMBE		VARCHAR(10),
	SPPLMNT_NU		VARCHAR(10),
	ITEM_NUMBE		VARCHAR(10),
	COLUMN_NUM		VARCHAR(10),
	FN_POINTER		VARCHAR(10),
	REPORT_PRD		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}88;
CREATE TABLE {schemaName}.{tableName}88
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	RESPONDEN2		VARCHAR(60),
	CHG_DT_PRE		VARCHAR(50),
	ADDR_PRNCP		VARCHAR(80),
	CNTC_NAME		VARCHAR(30),
	CNTC_TTL		VARCHAR(30),
	CNTC_ADDR		VARCHAR(80),
	CNTC_PHONE		VARCHAR(20),
	SUBMISSION		VARCHAR(10),
	RPT_DATE		VARCHAR(20),
	ATTESTATIO		VARCHAR(30),
	ATTESTATI2		VARCHAR(40),
	ATTESTATI3		VARCHAR(20),
	RESPONDEN3		BIGINT,
	CHG_DT_PR2		BIGINT,
	ADDR_PRNC2		BIGINT,
	CNTC_NAME_		BIGINT,
	CNTC_TTL_F		BIGINT,
	CNTC_ADDR_		BIGINT,
	CNTC_PHON2		BIGINT,
	SUBMISSIO2		BIGINT,
	RPT_DATE_F		BIGINT,
	ATTESTATI4		BIGINT,
	ATTESTATI5		BIGINT,
	ATTESTATI6		BIGINT,
	DATE_NAME_		VARCHAR(20),
	DATE_NAME2		BIGINT,
	REPORT_PRD		BIGINT,
	POC_EMAIL		VARCHAR(10),
	POC_EMAIL_		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}89;
CREATE TABLE {schemaName}.{tableName}89
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	PLANT_NAME		VARCHAR(30),
	PLANT_KIND		VARCHAR(30),
	TYPE_CONST		VARCHAR(30),
	YR_CONST		VARCHAR(100),
	YR_INSTALL		VARCHAR(100),
	TOT_CAPACI		VARCHAR(100),
	PEAK_DEMAN		BIGINT,
	PLANT_HOUR		BIGINT,
	PLNT_CAPAB		BIGINT,
	WHEN_NOT_L		BIGINT,
	WHEN_LIMIT		BIGINT,
	AVG_NUM_OF		BIGINT,
	NET_GENERA		BIGINT,
	COST_LAND		BIGINT,
	COST_STRUC		BIGINT,
	COST_EQUIP		BIGINT,
	COST_OF_PL		BIGINT,
	COST_PER_K		VARCHAR(100),
	EXPNS_OPER		BIGINT,
	EXPNS_FUEL		BIGINT,
	EXPNS_COOL		BIGINT,
	EXPNS_STEA		BIGINT,
	EXPNS_STE2		BIGINT,
	EXPNS_TRAN		BIGINT,
	EXPNS_ELEC		BIGINT,
	EXPNS_MISC		BIGINT,
	EXPNS_RENT		BIGINT,
	EXPNS_ALLO		BIGINT,
	EXPNS_ENGN		BIGINT,
	EXPNS_STRU		BIGINT,
	EXPNS_BOIL		BIGINT,
	EXPNS_PLAN		BIGINT,
	EXPNS_MIS2		BIGINT,
	TOT_PRDCTN		BIGINT,
	EXPNS_KWH		VARCHAR(100),
	PLANT_NAM2		BIGINT,
	PLANT_KIN2		BIGINT,
	TYPE_CONS2		BIGINT,
	YR_CONST_F		BIGINT,
	YR_INSTAL2		BIGINT,
	TOT_CAPAC2		BIGINT,
	PEAK_DEMA2		BIGINT,
	PLANT_HOU2		BIGINT,
	PLNT_CAPA2		BIGINT,
	WHEN_NOT_2		BIGINT,
	WHEN_LIMI2		BIGINT,
	AVG_NUM_O2		BIGINT,
	NET_GENER2		BIGINT,
	COST_LAND_		BIGINT,
	COST_STRU2		BIGINT,
	COST_EQUI2		BIGINT,
	COST_OF_P2		BIGINT,
	COST_PER_2		BIGINT,
	EXPNS_OPE2		BIGINT,
	EXPNS_FUE2		BIGINT,
	EXPNS_COO2		BIGINT,
	EXPNS_STE3		BIGINT,
	EXPNS_STE4		BIGINT,
	EXPNS_TRA2		BIGINT,
	EXPNS_ELE2		BIGINT,
	EXPNS_MIS3		BIGINT,
	EXPNS_REN2		BIGINT,
	EXPNS_ALL2		BIGINT,
	EXPNS_ENG2		BIGINT,
	EXPNS_STR2		BIGINT,
	EXPNS_BOI2		BIGINT,
	EXPNS_PLA2		BIGINT,
	EXPNS_MIS4		BIGINT,
	TOT_PRDCT2		BIGINT,
	EXPNS_KWH_		BIGINT,
	ASSET_RETI		BIGINT,
	ASSET_RET2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}9;
CREATE TABLE {schemaName}.{tableName}9
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	ACCT_DSC		VARCHAR(40),
	BGN_YR_BAL		BIGINT,
	CHG_YR_DR_		BIGINT,
	CHG_YR_CR_		BIGINT,
	CHG_YR_DR2		BIGINT,
	CHG_YR_CR2		BIGINT,
	DR_ADJ_ACC		VARCHAR(20),
	DR_ADJ_AMT		BIGINT,
	CR_ADJ_ACC		VARCHAR(20),
	CR_ADJ_AMT		BIGINT,
	END_YR_BAL		BIGINT,
	ACCT_DSC_F		BIGINT,
	BGN_YR_BA2		BIGINT,
	CHG_YR_DR3		BIGINT,
	CHG_YR_CR3		BIGINT,
	CHG_YR_DR4		BIGINT,
	CHG_YR_CR4		BIGINT,
	DR_ADJ_AC2		BIGINT,
	DR_ADJ_AM2		BIGINT,
	CR_ADJ_AC2		BIGINT,
	CR_ADJ_AM2		BIGINT,
	END_YR_BA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}90;
CREATE TABLE {schemaName}.{tableName}90
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	LESSEE		VARCHAR(40),
	DESCRIPTIO		VARCHAR(40),
	COMMISSION		VARCHAR(20),
	EXPIRATION		VARCHAR(20),
	BALANCE		BIGINT,
	LESSEE_F		BIGINT,
	DESCRIPTI2		BIGINT,
	COMMISSIO2		BIGINT,
	EXPIRATIO2		BIGINT,
	BALANCE_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}91;
CREATE TABLE {schemaName}.{tableName}91
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	INVSTMNT_D		VARCHAR(70),
	ACQUIRED_D		VARCHAR(20),
	MATURITY_D		VARCHAR(20),
	BEGINYR_IN		BIGINT,
	SBSDRY_EQT		BIGINT,
	YEAR_REVEN		BIGINT,
	YR_END_INV		BIGINT,
	GAIN_OR_LO		BIGINT,
	INVSTMNT_2		BIGINT,
	ACQUIRED_2		BIGINT,
	MATURITY_2		BIGINT,
	BEGINYR_I2		BIGINT,
	SBSDRY_EQ2		BIGINT,
	YEAR_REVE2		BIGINT,
	YR_END_IN2		BIGINT,
	GAIN_OR_L2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}92;
CREATE TABLE {schemaName}.{tableName}92
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESCRIPTIO		VARCHAR(60),
	DATE_ORIGI		VARCHAR(20),
	DATE_EXPEC		VARCHAR(20),
	BALANCE		BIGINT,
	DESCRIPTI2		BIGINT,
	DATE_ORIG2		BIGINT,
	DATE_EXPE2		BIGINT,
	BALANCE_F		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}93;
CREATE TABLE {schemaName}.{tableName}93
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	CLS_SERS_O		VARCHAR(90),
	PRNCPL_AMT		BIGINT,
	TOTAL_EXPE		BIGINT,
	PREMIUM_DS		VARCHAR(10),
	NOMINAL_IS		VARCHAR(20),
	MATURITY_D		VARCHAR(20),
	AMRTZDPER_		VARCHAR(20),
	AMRTZDPER2		VARCHAR(20),
	OUTSTANDIN		BIGINT,
	YR_AMT_INT		BIGINT,
	CLS_SERS_2		BIGINT,
	PRNCPL_AM2		BIGINT,
	TOTAL_EXP2		BIGINT,
	PREMIUM_D2		BIGINT,
	NOMINAL_I2		BIGINT,
	MATURITY_2		BIGINT,
	AMRTZDPER3		BIGINT,
	AMRTZDPER4		BIGINT,
	OUTSTANDI2		BIGINT,
	YR_AMT_IN2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}ALLOWANCES_NOX;
CREATE TABLE {schemaName}.{tableName}ALLOWANCES_NOX
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	SUCCEEDING		BIGINT,
	AI_BGNYRBA		VARCHAR(20),
	AI_BGNYRB2		VARCHAR(100),
	AI_ACQ_YR_		VARCHAR(100),
	AI_ACQ_YR2		VARCHAR(100),
	AI_EPA_RET		VARCHAR(100),
	AI_EPA_RE2		VARCHAR(100),
	PX_USERDEF		VARCHAR(30),
	PX_USERDE2		VARCHAR(100),
	PX_USERDE3		VARCHAR(100),
	PX_USERDE4		VARCHAR(30),
	PX_USERDE5		VARCHAR(100),
	PX_USERDE6		VARCHAR(100),
	PX_USERDE7		VARCHAR(30),
	PX_USERDE8		VARCHAR(100),
	PX_USERDE9		VARCHAR(100),
	PX_USERD10		VARCHAR(30),
	PX_USERD11		VARCHAR(100),
	PX_USERD12		VARCHAR(100),
	PX_USERD13		VARCHAR(20),
	PX_USERD14		VARCHAR(100),
	PX_USERD15		VARCHAR(100),
	PX_USERD16		VARCHAR(10),
	PX_USERD17		VARCHAR(100),
	PX_USERD18		VARCHAR(100),
	PX_USERD19		VARCHAR(10),
	PX_USERD20		VARCHAR(100),
	PX_USERD21		VARCHAR(100),
	PX_TOTAL_N		VARCHAR(100),
	PX_TOTAL_A		VARCHAR(100),
	RDY_CHARGE		VARCHAR(100),
	RDY_CHARG2		VARCHAR(100),
	RDY_OTHER_		VARCHAR(100),
	RDY_OTHER2		VARCHAR(100),
	RDY_USERDE		VARCHAR(30),
	RDY_USERD2		VARCHAR(100),
	RDY_USERD3		VARCHAR(100),
	SX_USERDEF		VARCHAR(30),
	SX_USERDE2		VARCHAR(100),
	SX_USERDE3		VARCHAR(100),
	SX_USERDE4		VARCHAR(30),
	SX_USERDE5		VARCHAR(100),
	SX_USERDE6		VARCHAR(100),
	SX_USERDE7		VARCHAR(30),
	SX_USERDE8		VARCHAR(100),
	SX_USERDE9		VARCHAR(100),
	SX_USERD10		VARCHAR(30),
	SX_USERD11		VARCHAR(100),
	SX_USERD12		VARCHAR(100),
	SX_USERD13		VARCHAR(30),
	SX_USERD14		VARCHAR(100),
	SX_USERD15		VARCHAR(100),
	SX_USERD16		VARCHAR(10),
	SX_USERD17		VARCHAR(100),
	SX_USERD18		VARCHAR(100),
	SX_TOTAL_N		VARCHAR(100),
	SX_TOTAL_A		VARCHAR(100),
	SX_YRENDBA		VARCHAR(100),
	SX_YRENDB2		VARCHAR(100),
	SX_NET_ASS		VARCHAR(100),
	SX_NET_AS2		VARCHAR(100),
	SX_NET_OTH		VARCHAR(100),
	SX_NET_OT2		VARCHAR(100),
	SX_GAINS_N		VARCHAR(100),
	SX_GAINS_A		VARCHAR(100),
	SX_LOSSES_		VARCHAR(100),
	SX_LOSSES2		VARCHAR(100),
	AW_BGNYRBA		VARCHAR(100),
	AW_BGNYRB2		VARCHAR(100),
	AW_WITHHEL		VARCHAR(100),
	AW_WITHHE2		VARCHAR(100),
	AW_RETURNE		VARCHAR(100),
	AW_RETURN2		VARCHAR(100),
	AW_SALES_N		VARCHAR(100),
	AW_SALES_A		VARCHAR(100),
	AW_YRENDBA		VARCHAR(100),
	AW_YRENDB2		VARCHAR(100),
	AW_NET_ASS		VARCHAR(100),
	AW_NET_AS2		VARCHAR(100),
	AW_NET_OTH		VARCHAR(100),
	AW_NET_OT2		VARCHAR(100),
	AW_GAINS_N		VARCHAR(100),
	AW_GAINS_A		VARCHAR(100),
	AW_LOSSES_		VARCHAR(100),
	AW_LOSSES2		VARCHAR(100),
	SUCCEEDIN2		BIGINT,
	AI_BGNYRB3		BIGINT,
	AI_BGNYRB4		BIGINT,
	AI_ACQ_YR3		BIGINT,
	AI_ACQ_YR4		BIGINT,
	AI_EPA_RE3		BIGINT,
	AI_EPA_RE4		BIGINT,
	PX_USERD22		BIGINT,
	PX_USERD23		BIGINT,
	PX_USERD24		BIGINT,
	PX_USERD25		BIGINT,
	PX_USERD26		BIGINT,
	PX_USERD27		BIGINT,
	PX_USERD28		BIGINT,
	PX_USERD29		BIGINT,
	PX_USERD30		BIGINT,
	PX_USERD31		BIGINT,
	PX_USERD32		BIGINT,
	PX_USERD33		BIGINT,
	PX_USERD34		BIGINT,
	PX_USERD35		BIGINT,
	PX_USERD36		BIGINT,
	PX_USERD37		BIGINT,
	PX_USERD38		BIGINT,
	PX_USERD39		BIGINT,
	PX_USERD40		BIGINT,
	PX_USERD41		BIGINT,
	PX_USERD42		BIGINT,
	PX_TOTAL_2		BIGINT,
	PX_TOTAL_3		BIGINT,
	RDY_CHARG3		BIGINT,
	RDY_CHARG4		BIGINT,
	RDY_OTHER3		BIGINT,
	RDY_OTHER4		BIGINT,
	RDY_USERD4		BIGINT,
	RDY_USERD5		BIGINT,
	RDY_USERD6		BIGINT,
	SX_USERD19		BIGINT,
	SX_USERD20		BIGINT,
	SX_USERD21		BIGINT,
	SX_USERD22		BIGINT,
	SX_USERD23		BIGINT,
	SX_USERD24		BIGINT,
	SX_USERD25		BIGINT,
	SX_USERD26		BIGINT,
	SX_USERD27		BIGINT,
	SX_USERD28		BIGINT,
	SX_USERD29		BIGINT,
	SX_USERD30		BIGINT,
	SX_USERD31		BIGINT,
	SX_USERD32		BIGINT,
	SX_USERD33		BIGINT,
	SX_USERD34		BIGINT,
	SX_USERD35		BIGINT,
	SX_USERD36		BIGINT,
	SX_TOTAL_2		BIGINT,
	SX_TOTAL_3		BIGINT,
	SX_YRENDB3		BIGINT,
	SX_YRENDB4		BIGINT,
	SX_NET_AS3		BIGINT,
	SX_NET_AS4		BIGINT,
	SX_NET_OT3		BIGINT,
	SX_NET_OT4		BIGINT,
	SX_GAINS_2		BIGINT,
	SX_GAINS_3		BIGINT,
	SX_LOSSES3		BIGINT,
	SX_LOSSES4		BIGINT,
	AW_BGNYRB3		BIGINT,
	AW_BGNYRB4		BIGINT,
	AW_WITHHE3		BIGINT,
	AW_WITHHE4		BIGINT,
	AW_RETURN3		BIGINT,
	AW_RETURN4		BIGINT,
	AW_SALES_2		BIGINT,
	AW_SALES_3		BIGINT,
	AW_YRENDB3		BIGINT,
	AW_YRENDB4		BIGINT,
	AW_NET_AS3		BIGINT,
	AW_NET_AS4		BIGINT,
	AW_NET_OT3		BIGINT,
	AW_NET_OT4		BIGINT,
	AW_GAINS_2		BIGINT,
	AW_GAINS_3		BIGINT,
	AW_LOSSES3		BIGINT,
	AW_LOSSES4		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}CMPINC_HEDGE;
CREATE TABLE {schemaName}.{tableName}CMPINC_HEDGE
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	UNREAL_GL_		VARCHAR(100),
	MIN_PEN_LI		VARCHAR(100),
	FOREIGN_CU		VARCHAR(100),
	OTHER_ADJ		VARCHAR(100),
	OTHER_CASH		VARCHAR(100),
	OTHER_CAS2		VARCHAR(100),
	TOT_CAT_21		VARCHAR(100),
	NET_INC_11		VARCHAR(100),
	TOT_COMP_I		VARCHAR(100),
	UNREAL_GL2		BIGINT,
	MIN_PEN_L2		BIGINT,
	FOREIGN_C2		BIGINT,
	OTHER_ADJ_		BIGINT,
	OTHER_CAS3		BIGINT,
	OTHER_CAS4		BIGINT,
	TOT_CAT_22		BIGINT,
	NET_INC_12		BIGINT,
	TOT_COMP_2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}CMPINC_HEDGE_A;
CREATE TABLE {schemaName}.{tableName}CMPINC_HEDGE_A
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	HEDGE1_CAT		VARCHAR(10),
	HEDGE2_CAT		VARCHAR(20),
	HEDGE1_CA2		BIGINT,
	HEDGE2_CA2		BIGINT,
	REPORT_PRD		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}EMAIL;
CREATE TABLE {schemaName}.{tableName}EMAIL
(
	RESPONDENT		BIGINT,
	LASTNAME		VARCHAR(20),
	FIRSTNAME		VARCHAR(30),
	EMAIL		VARCHAR(100),
	POC		BOOL,
	NOTIFY		VARCHAR(10),
	PHONE_NUM		VARCHAR(20),
	NOTES		VARCHAR(230)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}RG_TRN_SRV_REV;
CREATE TABLE {schemaName}.{tableName}RG_TRN_SRV_REV
(
	RESPONDENT		BIGINT,
	REPORT_YEA		BIGINT,
	REPORT_PRD		BIGINT,
	SPPLMNT_NU		BIGINT,
	ROW_NUMBER1		BIGINT,
	ROW_SEQ		BIGINT,
	ROW_PRVLG		VARCHAR(10),
	DESC_SERV		VARCHAR(50),
	BAL_END_Q1		VARCHAR(100),
	BAL_END_Q2		VARCHAR(100),
	BAL_END_Q3		VARCHAR(100),
	BAL_END_Q4		VARCHAR(100),
	DESC_SERV_		BIGINT,
	BAL_END_Q5		BIGINT,
	BAL_END_Q6		BIGINT,
	BAL_END_Q7		BIGINT,
	BAL_END_Q8		INT
);

DROP TABLE IF EXISTS {schemaName}.{tableName}S0_CHECKS;
CREATE TABLE {schemaName}.{tableName}S0_CHECKS
(
	REPORT_YR		BIGINT,
	REPORT_PRD		BIGINT,
	CHECK_ID		BIGINT,
	OTHER_ID		VARCHAR(10),
	CHECK_GROU		VARCHAR(10),
	CHECK_DESC		VARCHAR(110),
	EQUATION1		VARCHAR(1170),
	EQUATION2		VARCHAR(10),
	VARIANCE_A		VARCHAR(100),
	VARIANCE_P		VARCHAR(100),
	ERROR_CHEC		VARCHAR(10)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}S0_FILING_LOG;
CREATE TABLE {schemaName}.{tableName}S0_FILING_LOG
(
	RESPONDENT		BIGINT,
	REPORT_YR		BIGINT,
	REPORT_PRD		BIGINT,
	FILING_NUM		BIGINT,
	POC_EMAIL		VARCHAR(40),
	SUBMITTED		VARCHAR(20),
	RECEIVED		VARCHAR(20),
	LOADED			VARCHAR(20),
	MISC			VARCHAR(10),
	FILING_NOT		VARCHAR(660)
);

DROP TABLE IF EXISTS {schemaName}.{tableName}SECURITY;
CREATE TABLE {schemaName}.{tableName}SECURITY
(
	RESPONDENT		BIGINT,
	PSWD_DOWNL		VARCHAR(10)
);

